Repository navikt/bidrag-beregn-felles, pull requests merged in 2024-12, with the labels that each got.

#421 Feilfiks andre voksne i husstanden beregning
  bidrag-boforhold/src/main/kotlin/no/nav/bidrag/boforhold/service/BoforholdAndreVoksneService.kt
Labels: bugfix

#427 Ikke åpen sluttperiode hvis søknadsbarnet fyller 18 år i beregningspe…
  bidrag-beregn-barnebidrag/src/main/kotlin/no/nav/bidrag/beregn/barnebidrag/service/BeregnBarnebidragService.kt
  bidrag-beregn-barnebidrag/src/test/kotlin/no/nav/bidrag/beregn/barnebidrag/api/BeregnBarnebidragApiTest.kt
Labels: feature

#429 Fiks sjablon referanse for maks tilsyn og maks fradrag
  bidrag-beregn-core/src/main/kotlin/no/nav/bidrag/beregn/core/mapping/SjablonTilGrunnlagMapping.kt
Labels: bidrag-beregn-core, feature

#432 Barn under tolv år 1.juli
  bidrag-beregn-barnebidrag/src/main/kotlin/no/nav/bidrag/beregn/barnebidrag/service/BeregnNettoTilsynsutgiftService.kt
Labels: feature

#433 Feature/barnetillegg skattesats
  bidrag-beregn-barnebidrag/src/main/kotlin/no/nav/bidrag/beregn/barnebidrag/beregning/BarnetilleggSkattesatsBeregning.kt
  bidrag-beregn-barnebidrag/src/main/kotlin/no/nav/bidrag/beregn/barnebidrag/bo/BarnetilleggSkattesatsBO.kt
  bidrag-beregn-barnebidrag/src/main/kotlin/no/nav/bidrag/beregn/barnebidrag/service/BeregnBarnetilleggSkattesatsService.kt
  bidrag-beregn-barnebidrag/src/test/kotlin/no/nav/bidrag/beregn/barnebidrag/api/BeregnBarnetilleggSkattesatsApiTest.kt
  bidrag-beregn-barnebidrag/src/test/resources/testfiler/nettobarnetillegg/netto_barnetillegg_eksempel1.json
  bidrag-beregn-barnebidrag/src/test/resources/testfiler/nettobarnetillegg/netto_barnetillegg_eksempel2.json
  bidrag-beregn-barnebidrag/src/test/resources/testfiler/nettobarnetillegg/netto_barnetillegg_eksempel4_periodisering.json
  pom.xml
Labels: feature

#434 Feature/brudd fødselsdato
  bidrag-beregn-barnebidrag/src/main/kotlin/no/nav/bidrag/beregn/barnebidrag/bo/BarnetilleggSkattesatsBO.kt
  bidrag-beregn-barnebidrag/src/main/kotlin/no/nav/bidrag/beregn/barnebidrag/mapper/BidragsevneMapper.kt
  bidrag-beregn-barnebidrag/src/main/kotlin/no/nav/bidrag/beregn/barnebidrag/service/BeregnBarnebidragService.kt
  bidrag-beregn-barnebidrag/src/main/kotlin/no/nav/bidrag/beregn/barnebidrag/service/BeregnBarnetilleggSkattesatsService.kt
  bidrag-beregn-barnebidrag/src/main/kotlin/no/nav/bidrag/beregn/barnebidrag/service/BeregnNettoTilsynsutgiftService.kt
  bidrag-beregn-barnebidrag/src/test/kotlin/no/nav/bidrag/beregn/barnebidrag/api/BeregnNettoBarnetilleggApiTest.kt
  bidrag-beregn-barnebidrag/src/test/kotlin/no/nav/bidrag/beregn/barnebidrag/api/BeregnNettoTilsynsutgiftApiTest.kt
  bidrag-beregn-barnebidrag/src/test/kotlin/no/nav/bidrag/beregn/barnebidrag/api/BeregnNettoTilsynsutgiftOgUnderholdskostnadApiTest.kt
  bidrag-beregn-barnebidrag/src/test/kotlin/no/nav/bidrag/beregn/barnebidrag/api/BeregnUnderholdskostnadApiTest.kt
  bidrag-beregn-barnebidrag/src/test/resources/testfiler/nettobarnetilsynogunderholdskostnad/nettotilsynsutgift_og_underholdskostnad_flere_barn.json
  bidrag-beregn-barnebidrag/src/test/resources/testfiler/nettotilsynsutgift/nettotilsynsutgift_barnoverogundertolvår.json
  bidrag-beregn-core/src/main/kotlin/no/nav/bidrag/beregn/core/service/mapper/CoreMapper.kt
  pom.xml
Labels: bidrag-beregn-core, feature

#438 Beregnet antall barn BM i perioden
  bidrag-beregn-barnebidrag/src/main/kotlin/no/nav/bidrag/beregn/barnebidrag/beregning/NettoTilsynsutgiftBeregning.kt
  bidrag-beregn-barnebidrag/src/main/kotlin/no/nav/bidrag/beregn/barnebidrag/bo/NettoTilsynsutgiftBO.kt
  bidrag-beregn-barnebidrag/src/main/kotlin/no/nav/bidrag/beregn/barnebidrag/mapper/NettoTilsynsutgiftMapper.kt
  bidrag-beregn-barnebidrag/src/main/kotlin/no/nav/bidrag/beregn/barnebidrag/service/BeregnNettoTilsynsutgiftService.kt
  bidrag-beregn-barnebidrag/src/test/resources/testfiler/nettotilsynsutgift/nettotilsynsutgift_eksempel_flere_perioder.json
  pom.xml
Labels: feature
