Repository navikt/bidrag-beregn-felles, pull requests merged in 2024-07, with the labels that each got.

#250 Rettet feil i beregning av overgangsstønad når beløp er 0 - sak 2203080
  bidrag-inntekt/src/main/kotlin/no/nav/bidrag/inntekt/service/YtelserServiceOvergangsstønad.kt
Labels: bidrag-inntekt, bugfix

#254 Lagt inn krav til at husstandsmedlemskap har vart i over én måned bof…
  bidrag-boforhold/src/main/kotlin/no/nav/bidrag/boforhold/service/BoforholdAndreVoksneService.kt
  bidrag-boforhold/src/test/kotlin/no/nav/bidrag/boforhold/TestUtil.kt
  bidrag-boforhold/src/test/kotlin/no/nav/bidrag/boforhold/service/BoforholdAndreVoksneServiceTest.kt
Labels: feature

#255 Ny versjon av bidrag-felles (liten justering på et par objekter som p…
  bidrag-beregn-forskudd/src/main/kotlin/no/nav/bidrag/beregn/forskudd/service/BeregnForskuddService.kt
  pom.xml
Labels: bidrag-beregn-forskudd, feature

#256 Endret litt på forskuddsberegningen for å få den i samsvar med Bisys …
  bidrag-beregn-forskudd/src/main/kotlin/no/nav/bidrag/beregn/forskudd/core/ForskuddBeregning.kt
  bidrag-beregn-forskudd/src/test/kotlin/no/nav/bidrag/beregn/forskudd/api/BeregnForskuddApiTest.kt
  bidrag-beregn-forskudd/src/test/kotlin/no/nav/bidrag/beregn/forskudd/core/ForskuddBeregningTest.kt
Labels: bidrag-beregn-forskudd, bugfix

#257 Endre bidragsmottakerIdent til gjelderIdent i BeregnInntekt request
  bidrag-beregn-core/src/main/kotlin/no/nav/bidrag/beregn/core/BeregnApi.kt
  bidrag-beregn-core/src/main/kotlin/no/nav/bidrag/beregn/core/inntekt/service/BeregnInntektService.kt
  bidrag-beregn-core/src/main/kotlin/no/nav/bidrag/beregn/core/util/InntektUtil.kt
  bidrag-beregn-core/src/test/resources/testfiler/summer_inntekter_request_eksempel1.json
  bidrag-boforhold/src/main/kotlin/no/nav/bidrag/boforhold/service/BoforholdAndreVoksneService.kt
  pom.xml
Labels: bidrag-beregn-core, feature

#258 Fiks feil i boforhold api v3 hvor noen perioder ble borte i responsen
  bidrag-boforhold/src/main/kotlin/no/nav/bidrag/boforhold/dto/Boforhold.kt
  bidrag-boforhold/src/main/kotlin/no/nav/bidrag/boforhold/service/BoforholdBarnServiceV3.kt
Labels: bugfix

#259 Andre voksne i husstand returner default verdi hvis tom liste
  bidrag-boforhold/src/main/kotlin/no/nav/bidrag/boforhold/service/BoforholdAndreVoksneService.kt
Labels: bugfix

#262 Refaktorering (oppdatert avhengigheter, fjernet duplisert kode, gjort…
  bidrag-beregn-core/src/main/kotlin/no/nav/bidrag/beregn/core/bo/Sjablon.kt
  bidrag-beregn-core/src/main/kotlin/no/nav/bidrag/beregn/core/dto/CoreDto.kt
  bidrag-beregn-core/src/main/kotlin/no/nav/bidrag/beregn/core/exception/ExceptionHandlerAdvice.kt
  bidrag-beregn-core/src/main/kotlin/no/nav/bidrag/beregn/core/exception/SjablonConsumerException.kt
  bidrag-beregn-core/src/main/kotlin/no/nav/bidrag/beregn/core/exception/UgyldigInputException.kt
  bidrag-beregn-core/src/main/kotlin/no/nav/bidrag/beregn/core/inntekt/Inntekt.kt
  bidrag-beregn-core/src/main/kotlin/no/nav/bidrag/beregn/core/periode/Periodiserer.kt
  bidrag-beregn-core/src/main/kotlin/no/nav/bidrag/beregn/core/service/BeregnService.kt
  bidrag-beregn-core/src/main/kotlin/no/nav/bidrag/beregn/core/service/mapper/CoreMapper.kt
  bidrag-beregn-core/src/main/kotlin/no/nav/bidrag/beregn/core/util/InntektUtil.kt
  bidrag-beregn-core/src/main/kotlin/no/nav/bidrag/beregn/core/util/SjablonUtil.kt
  bidrag-beregn-core/src/test/kotlin/no/nav/bidrag/beregn/core/TestUtil.kt
  bidrag-beregn-core/src/test/kotlin/no/nav/bidrag/beregn/core/inntekt/InntektTest.kt
  bidrag-beregn-core/src/test/kotlin/no/nav/bidrag/beregn/core/periode/OverlappendePerioderTest.kt
  bidrag-beregn-core/src/test/kotlin/no/nav/bidrag/beregn/core/periode/PeriodeValideringTest.kt
  bidrag-beregn-core/src/test/kotlin/no/nav/bidrag/beregn/core/periode/PeriodisererTest.kt
  bidrag-beregn-core/src/test/kotlin/no/nav/bidrag/beregn/core/sjablon/SjablonTest.kt
  bidrag-beregn-forskudd/src/main/kotlin/no/nav/bidrag/beregn/forskudd/core/ForskuddBeregning.kt
  bidrag-beregn-forskudd/src/main/kotlin/no/nav/bidrag/beregn/forskudd/core/ForskuddCore.kt
  bidrag-beregn-forskudd/src/main/kotlin/no/nav/bidrag/beregn/forskudd/core/dto/CoreDTO.kt
  bidrag-beregn-forskudd/src/main/kotlin/no/nav/bidrag/beregn/forskudd/core/periode/ForskuddPeriode.kt
  bidrag-beregn-forskudd/src/main/kotlin/no/nav/bidrag/beregn/forskudd/service/BeregnForskuddService.kt
  bidrag-beregn-forskudd/src/main/kotlin/no/nav/bidrag/beregn/forskudd/service/CoreMapper.kt
  bidrag-beregn-forskudd/src/main/kotlin/no/nav/bidrag/beregn/forskudd/service/ForskuddCoreMapper.kt
  bidrag-beregn-forskudd/src/test/kotlin/no/nav/bidrag/beregn/forskudd/TestUtil.kt
  bidrag-beregn-forskudd/src/test/kotlin/no/nav/bidrag/beregn/forskudd/core/ForskuddBeregningTest.kt
  bidrag-beregn-forskudd/src/test/kotlin/no/nav/bidrag/beregn/forskudd/service/BeregnForskuddServiceTest.kt
  bidrag-beregn-forskudd/src/test/kotlin/no/nav/bidrag/beregn/forskudd/service/ForskuddCoreMapperTest.kt
  bidrag-beregn-særbidrag/src/main/kotlin/no/nav/bidrag/beregn/særbidrag/core/bidragsevne/BidragsevneCore.kt
  bidrag-beregn-særbidrag/src/main/kotlin/no/nav/bidrag/beregn/særbidrag/core/bidragsevne/beregning/BidragsevneBeregning.kt
  bidrag-beregn-særbidrag/src/main/kotlin/no/nav/bidrag/beregn/særbidrag/core/bidragsevne/dto/CoreDTO.kt
  bidrag-beregn-særbidrag/src/main/kotlin/no/nav/bidrag/beregn/særbidrag/core/bidragsevne/periode/BidragsevnePeriode.kt
  bidrag-beregn-særbidrag/src/main/kotlin/no/nav/bidrag/beregn/særbidrag/core/bpsandelsærbidrag/BPsAndelSærbidragCore.kt
  bidrag-beregn-særbidrag/src/main/kotlin/no/nav/bidrag/beregn/særbidrag/core/bpsandelsærbidrag/dto/CoreDTO.kt
  bidrag-beregn-særbidrag/src/main/kotlin/no/nav/bidrag/beregn/særbidrag/core/bpsandelsærbidrag/periode/BPsAndelSærbidragPeriode.kt
  bidrag-beregn-særbidrag/src/main/kotlin/no/nav/bidrag/beregn/særbidrag/core/felles/FellesCore.kt
  bidrag-beregn-særbidrag/src/main/kotlin/no/nav/bidrag/beregn/særbidrag/core/felles/dto/CoreDTO.kt
  bidrag-beregn-særbidrag/src/main/kotlin/no/nav/bidrag/beregn/særbidrag/core/særbidrag/periode/SærbidragPeriode.kt
  bidrag-beregn-særbidrag/src/main/kotlin/no/nav/bidrag/beregn/særbidrag/service/BeregnSærbidragService.kt
  bidrag-beregn-særbidrag/src/main/kotlin/no/nav/bidrag/beregn/særbidrag/service/mapper/BPAndelSærbidragCoreMapper.kt
  bidrag-beregn-særbidrag/src/main/kotlin/no/nav/bidrag/beregn/særbidrag/service/mapper/BidragsevneCoreMapper.kt
  bidrag-beregn-særbidrag/src/main/kotlin/no/nav/bidrag/beregn/særbidrag/service/mapper/SærbidragCoreMapper.kt
  bidrag-beregn-særbidrag/src/test/kotlin/no/nav/bidrag/beregn/særbidrag/TestUtil.kt
  bidrag-beregn-særbidrag/src/test/kotlin/no/nav/bidrag/beregn/særbidrag/core/bidragsevne/BidragsevneCoreTest.kt
  bidrag-beregn-særbidrag/src/test/kotlin/no/nav/bidrag/beregn/særbidrag/core/bidragsevne/BidragsevnePeriodeTest.kt
  bidrag-beregn-særbidrag/src/test/kotlin/no/nav/bidrag/beregn/særbidrag/core/bpsandelsærbidrag/BPsAndelSærbidragCoreTest.kt
  bidrag-beregn-særbidrag/src/test/kotlin/no/nav/bidrag/beregn/særbidrag/core/bpsandelsærbidrag/BPsAndelSærbidragPeriodeTest.kt
  bidrag-beregn-særbidrag/src/test/kotlin/no/nav/bidrag/beregn/særbidrag/core/særbidrag/SærbidragPeriodeTest.kt
  bidrag-beregn-særbidrag/src/test/kotlin/no/nav/bidrag/beregn/særbidrag/service/BeregnSærbidragServiceTest.kt
  bidrag-inntekt/pom.xml
  bidrag-inntekt/src/main/kotlin/no/nav/bidrag/inntekt/service/AinntektService.kt
  bidrag-inntekt/src/main/kotlin/no/nav/bidrag/inntekt/service/InntektService.kt
  bidrag-inntekt/src/test/kotlin/no/nav/bidrag/inntekt/service/AinntektServiceTest.kt
  pom.xml
Labels: bidrag-beregn-forskudd, bidrag-beregn-core, bidrag-inntekt, feature

#268 Feilfiks status REGNES_IKKE_SOM_BARN for 18 åring beregning v3
  bidrag-boforhold/src/main/kotlin/no/nav/bidrag/boforhold/service/BoforholdBarnServiceV3.kt
Labels: bugfix

#270 Feilfiks opprettelse av referanse for delberegning
  bidrag-beregn-core/src/main/kotlin/no/nav/bidrag/beregn/core/service/mapper/CoreMapper.kt
  bidrag-beregn-forskudd/src/main/kotlin/no/nav/bidrag/beregn/forskudd/service/ForskuddCoreMapper.kt
  bidrag-beregn-forskudd/src/test/kotlin/no/nav/bidrag/beregn/forskudd/service/ForskuddCoreMapperTest.kt
  bidrag-beregn-særbidrag/src/main/kotlin/no/nav/bidrag/beregn/særbidrag/service/mapper/BidragsevneCoreMapper.kt
  pom.xml
Labels: bidrag-beregn-forskudd, bidrag-beregn-core, bugfix

#273 Nytt felt i BoforholdBarnRequestV3 typeBehandling. Brukes til å kunne…
  bidrag-boforhold/src/main/kotlin/no/nav/bidrag/boforhold/dto/Boforhold.kt
  bidrag-boforhold/src/main/kotlin/no/nav/bidrag/boforhold/service/BoforholdBarnServiceV3.kt
  bidrag-boforhold/src/test/kotlin/no/nav/bidrag/boforhold/TestUtil.kt
  bidrag-boforhold/src/test/kotlin/no/nav/bidrag/boforhold/service/BoforholdBarnServiceV3Test.kt
  pom.xml
Labels: feature

#274 typeBehandling flyttet ett nivå opp, boforholdBarn
  bidrag-boforhold/src/main/kotlin/no/nav/bidrag/boforhold/BoforholdApi.kt
  bidrag-boforhold/src/main/kotlin/no/nav/bidrag/boforhold/dto/Boforhold.kt
  bidrag-boforhold/src/main/kotlin/no/nav/bidrag/boforhold/service/BoforholdBarnServiceV3.kt
  bidrag-boforhold/src/test/kotlin/no/nav/bidrag/boforhold/TestUtil.kt
  bidrag-boforhold/src/test/kotlin/no/nav/bidrag/boforhold/service/BoforholdBarnServiceV3Test.kt
Labels: feature

#275 Oppdater felles
  pom.xml
Labels: feature

#269 Trigger ny deploy pga feil ved release
  README.md
Labels: documentation
