Repository navikt/bidrag-beregn-felles, pull requests merged in 2024-08, with the labels that each got.

#277 Trigge ny release
  README.md
Labels: documentation

#280 Forskudd delberegning inntekt referanse til bidragsmottaker
  bidrag-beregn-forskudd/src/main/kotlin/no/nav/bidrag/beregn/forskudd/service/BeregnForskuddService.kt
  bidrag-beregn-forskudd/src/main/kotlin/no/nav/bidrag/beregn/forskudd/service/ForskuddCoreMapper.kt
Labels: bidrag-beregn-forskudd, feature

#281 Lagt til kontroll på om godkjent beløp er høyere enn forskuddssats pl…
  bidrag-beregn-core/src/main/kotlin/no/nav/bidrag/beregn/core/service/BeregnService.kt
  bidrag-beregn-særbidrag/src/main/kotlin/no/nav/bidrag/beregn/særbidrag/core/bpsandelsærbidrag/beregning/BPsAndelSærbidragBeregning.kt
  bidrag-beregn-særbidrag/src/main/kotlin/no/nav/bidrag/beregn/særbidrag/service/BeregnSærbidragService.kt
  bidrag-beregn-særbidrag/src/test/kotlin/no/nav/bidrag/beregn/særbidrag/api/BeregnSærbidragApiTest.kt
  bidrag-beregn-særbidrag/src/test/resources/testfiler/særbidrag_eksempel_beløp_under_forskuddssats.json
  pom.xml
Labels: bidrag-beregn-core, feature

#284 Oppdater beregning resultatkode godkjent beløp lavere enn forskuddssats
  bidrag-beregn-særbidrag/src/main/kotlin/no/nav/bidrag/beregn/særbidrag/service/BeregnSærbidragService.kt
  bidrag-beregn-særbidrag/src/test/kotlin/no/nav/bidrag/beregn/særbidrag/api/BeregnSærbidragApiTest.kt
  pom.xml
Labels: feature

#285 Endrer sjekk på inntektstype for å utelate fratrekk for kapitalinntek…
  bidrag-beregn-core/src/main/kotlin/no/nav/bidrag/beregn/core/util/InntektUtil.kt
  bidrag-beregn-særbidrag/src/test/kotlin/no/nav/bidrag/beregn/særbidrag/api/BeregnSærbidragApiTest.kt
  bidrag-beregn-særbidrag/src/test/resources/testfiler/særbidrag_eksempel_inntekt_skjønn_mangler_dokumentasjon.json
Labels: bidrag-beregn-core

#286 Vedtakstype tatt med i request beregning særbidrag for å skille fasts…
  bidrag-beregn-særbidrag/src/main/kotlin/no/nav/bidrag/beregn/særbidrag/BeregnSærbidragApi.kt
  bidrag-beregn-særbidrag/src/main/kotlin/no/nav/bidrag/beregn/særbidrag/service/BeregnSærbidragService.kt
  bidrag-beregn-særbidrag/src/test/kotlin/no/nav/bidrag/beregn/særbidrag/api/BeregnSærbidragApiTest.kt
  bidrag-beregn-særbidrag/src/test/kotlin/no/nav/bidrag/beregn/særbidrag/service/BeregnSærbidragServiceTest.kt
Labels: feature

#289 Egen api for validering av særbidrag for beregning
  bidrag-beregn-særbidrag/src/main/kotlin/no/nav/bidrag/beregn/særbidrag/ValiderSærbidragForBeregningService.kt
  bidrag-beregn-særbidrag/src/main/kotlin/no/nav/bidrag/beregn/særbidrag/service/BeregnSærbidragService.kt
Labels: feature

#290 Endre særbidrag beregning beløp null ved avslag
  bidrag-beregn-særbidrag/src/main/kotlin/no/nav/bidrag/beregn/særbidrag/core/særbidrag/beregning/SærbidragBeregning.kt
  bidrag-beregn-særbidrag/src/main/kotlin/no/nav/bidrag/beregn/særbidrag/core/særbidrag/bo/CoreBO.kt
  bidrag-beregn-særbidrag/src/main/kotlin/no/nav/bidrag/beregn/særbidrag/core/særbidrag/dto/CoreDTO.kt
  bidrag-beregn-særbidrag/src/main/kotlin/no/nav/bidrag/beregn/særbidrag/service/BeregnSærbidragService.kt
  bidrag-beregn-særbidrag/src/test/kotlin/no/nav/bidrag/beregn/særbidrag/api/BeregnSærbidragApiTest.kt
  bidrag-beregn-særbidrag/src/test/kotlin/no/nav/bidrag/beregn/særbidrag/core/særbidrag/SærbidragBeregningTest.kt
  pom.xml
Labels: feature

#291 Endre særbidrag beregning fra andelProsent til andelFaktor
  bidrag-beregn-særbidrag/src/main/kotlin/no/nav/bidrag/beregn/særbidrag/core/bpsandelsærbidrag/BPsAndelSærbidragCore.kt
  bidrag-beregn-særbidrag/src/main/kotlin/no/nav/bidrag/beregn/særbidrag/core/bpsandelsærbidrag/beregning/BPsAndelSærbidragBeregning.kt
  bidrag-beregn-særbidrag/src/main/kotlin/no/nav/bidrag/beregn/særbidrag/core/bpsandelsærbidrag/bo/CoreBO.kt
  bidrag-beregn-særbidrag/src/main/kotlin/no/nav/bidrag/beregn/særbidrag/core/bpsandelsærbidrag/dto/CoreDTO.kt
  bidrag-beregn-særbidrag/src/main/kotlin/no/nav/bidrag/beregn/særbidrag/core/særbidrag/SærbidragCore.kt
  bidrag-beregn-særbidrag/src/main/kotlin/no/nav/bidrag/beregn/særbidrag/core/særbidrag/bo/CoreBO.kt
  bidrag-beregn-særbidrag/src/main/kotlin/no/nav/bidrag/beregn/særbidrag/core/særbidrag/bo/Periode.kt
  bidrag-beregn-særbidrag/src/main/kotlin/no/nav/bidrag/beregn/særbidrag/core/særbidrag/dto/CoreDTO.kt
  bidrag-beregn-særbidrag/src/main/kotlin/no/nav/bidrag/beregn/særbidrag/core/særbidrag/periode/SærbidragPeriode.kt
  bidrag-beregn-særbidrag/src/main/kotlin/no/nav/bidrag/beregn/særbidrag/service/BeregnSærbidragService.kt
  bidrag-beregn-særbidrag/src/main/kotlin/no/nav/bidrag/beregn/særbidrag/service/mapper/SærbidragCoreMapper.kt
  bidrag-beregn-særbidrag/src/test/kotlin/no/nav/bidrag/beregn/særbidrag/TestUtil.kt
  bidrag-beregn-særbidrag/src/test/kotlin/no/nav/bidrag/beregn/særbidrag/api/BeregnSærbidragApiTest.kt
  bidrag-beregn-særbidrag/src/test/kotlin/no/nav/bidrag/beregn/særbidrag/core/bpsandelsærbidrag/BPsAndelSærbidragBeregningTest.kt
  bidrag-beregn-særbidrag/src/test/kotlin/no/nav/bidrag/beregn/særbidrag/core/bpsandelsærbidrag/BPsAndelSærbidragCoreTest.kt
  bidrag-beregn-særbidrag/src/test/kotlin/no/nav/bidrag/beregn/særbidrag/core/bpsandelsærbidrag/BPsAndelSærbidragPeriodeTest.kt
  bidrag-beregn-særbidrag/src/test/kotlin/no/nav/bidrag/beregn/særbidrag/core/særbidrag/SærbidragBeregningTest.kt
  bidrag-beregn-særbidrag/src/test/kotlin/no/nav/bidrag/beregn/særbidrag/core/særbidrag/SærbidragCoreTest.kt
  bidrag-beregn-særbidrag/src/test/kotlin/no/nav/bidrag/beregn/særbidrag/core/særbidrag/SærbidragPeriodeTest.kt
  pom.xml
Labels: feature

#292 Særbidrag oppdater tester
  bidrag-beregn-særbidrag/src/test/kotlin/no/nav/bidrag/beregn/særbidrag/TestUtil.kt
  bidrag-beregn-særbidrag/src/test/kotlin/no/nav/bidrag/beregn/særbidrag/core/bpsandelsærbidrag/BPsAndelSærbidragCoreTest.kt
  bidrag-beregn-særbidrag/src/test/kotlin/no/nav/bidrag/beregn/særbidrag/core/bpsandelsærbidrag/BPsAndelSærbidragPeriodeTest.kt
  bidrag-beregn-særbidrag/src/test/kotlin/no/nav/bidrag/beregn/særbidrag/core/særbidrag/SærbidragBeregningTest.kt
  bidrag-beregn-særbidrag/src/test/kotlin/no/nav/bidrag/beregn/særbidrag/core/særbidrag/SærbidragCoreTest.kt
  bidrag-beregn-særbidrag/src/test/kotlin/no/nav/bidrag/beregn/særbidrag/core/særbidrag/SærbidragPeriodeTest.kt
  bidrag-inntekt/src/main/kotlin/no/nav/bidrag/inntekt/service/SkattegrunnlagService.kt
  bidrag-inntekt/src/main/kotlin/no/nav/bidrag/inntekt/util/InntektUtil.kt
  bidrag-inntekt/src/main/kotlin/no/nav/bidrag/inntekt/util/PostMappingUtil.kt
Labels: bidrag-inntekt, feature

#293 Inntekt api for å hente faktor for kapitalinntekt
  bidrag-inntekt/src/main/kotlin/no/nav/bidrag/inntekt/util/InntektUtil.kt
Labels: bidrag-inntekt, feature
