Repository navikt/bidrag-beregn-felles, pull requests merged in 2024-11, with the labels that each got.

#364 Endre samværskalkulator til å beregne gjennomsnittligMånedligSamvær på samme måte som offentlig kalkulator
  bidrag-beregn-barnebidrag/src/main/kotlin/no/nav/bidrag/beregn/barnebidrag/BeregnSamværsklasseApi.kt
  bidrag-beregn-barnebidrag/src/test/kotlin/no/nav/bidrag/beregn/barnebidrag/BeregnSamværsklasseApiTest.kt
Labels: feature

#365 Feilfiks samværskalkulator
  bidrag-beregn-barnebidrag/src/main/kotlin/no/nav/bidrag/beregn/barnebidrag/BeregnSamværsklasseApi.kt
  bidrag-beregn-barnebidrag/src/test/kotlin/no/nav/bidrag/beregn/barnebidrag/BeregnSamværsklasseApiTest.kt
  pom.xml
Labels: bugfix

#371 Samværskalkulator grunnlag
  bidrag-beregn-barnebidrag/src/main/kotlin/no/nav/bidrag/beregn/barnebidrag/BeregnSamværsklasseApi.kt
  bidrag-beregn-barnebidrag/src/main/kotlin/no/nav/bidrag/beregn/barnebidrag/mapper/SamværsfradragMapper.kt
  bidrag-beregn-barnebidrag/src/test/kotlin/no/nav/bidrag/beregn/barnebidrag/BeregnSamværsklasseApiTest.kt
  bidrag-beregn-barnebidrag/src/test/kotlin/no/nav/bidrag/beregn/barnebidrag/api/BeregnSamværsfradragApiTest.kt
  bidrag-beregn-core/src/main/kotlin/no/nav/bidrag/beregn/core/mapping/SjablonTilGrunnlagMapping.kt
  bidrag-beregn-core/src/main/kotlin/no/nav/bidrag/beregn/core/service/BeregnService.kt
  bidrag-beregn-core/src/main/kotlin/no/nav/bidrag/beregn/core/util/SjablonUtil.kt
  bidrag-beregn-særbidrag/src/main/kotlin/no/nav/bidrag/beregn/særbidrag/service/BeregnSærbidragService.kt
  pom.xml
Labels: bidrag-beregn-core, feature

#373 Refaktorering av samværsklasse api
  bidrag-beregn-barnebidrag/src/main/kotlin/no/nav/bidrag/beregn/barnebidrag/BeregnSamværsklasseApi.kt
  bidrag-beregn-barnebidrag/src/test/kotlin/no/nav/bidrag/beregn/barnebidrag/BeregnSamværsklasseApiTest.kt
  pom.xml
Labels: feature

#370 Feature/barnebidrag sluttberegning
  bidrag-beregn-barnebidrag/src/main/kotlin/no/nav/bidrag/beregn/barnebidrag/BeregnBarnebidragApi.kt
  bidrag-beregn-barnebidrag/src/main/kotlin/no/nav/bidrag/beregn/barnebidrag/BeregnSamværsklasseApi.kt
  bidrag-beregn-barnebidrag/src/main/kotlin/no/nav/bidrag/beregn/barnebidrag/beregning/BidragsevneBeregning.kt
  bidrag-beregn-barnebidrag/src/main/kotlin/no/nav/bidrag/beregn/barnebidrag/beregning/EndeligBidragBeregning.kt
  bidrag-beregn-barnebidrag/src/main/kotlin/no/nav/bidrag/beregn/barnebidrag/bo/BidragsevneBO.kt
  bidrag-beregn-barnebidrag/src/main/kotlin/no/nav/bidrag/beregn/barnebidrag/bo/BpAndelUnderholdskostnadBO.kt
  bidrag-beregn-barnebidrag/src/main/kotlin/no/nav/bidrag/beregn/barnebidrag/bo/EndeligBidragBO.kt
  bidrag-beregn-barnebidrag/src/main/kotlin/no/nav/bidrag/beregn/barnebidrag/bo/FellesBO.kt
  bidrag-beregn-barnebidrag/src/main/kotlin/no/nav/bidrag/beregn/barnebidrag/bo/NettoTilsynsutgiftGrunnlagResultat.kt~
  bidrag-beregn-barnebidrag/src/main/kotlin/no/nav/bidrag/beregn/barnebidrag/mapper/BidragsevneMapper.kt
  bidrag-beregn-barnebidrag/src/main/kotlin/no/nav/bidrag/beregn/barnebidrag/mapper/BpAndelUnderholdskostnadMapper.kt
  bidrag-beregn-barnebidrag/src/main/kotlin/no/nav/bidrag/beregn/barnebidrag/mapper/EndeligBidragMapper.kt
  bidrag-beregn-barnebidrag/src/main/kotlin/no/nav/bidrag/beregn/barnebidrag/mapper/NettoTilsynsutgiftMapper.kt
  bidrag-beregn-barnebidrag/src/main/kotlin/no/nav/bidrag/beregn/barnebidrag/service/BeregnBarnebidragService.kt
  bidrag-beregn-barnebidrag/src/main/kotlin/no/nav/bidrag/beregn/barnebidrag/service/BeregnBidragsevneService.kt
  bidrag-beregn-barnebidrag/src/main/kotlin/no/nav/bidrag/beregn/barnebidrag/service/BeregnBpAndelUnderholdskostnadService.kt
  bidrag-beregn-barnebidrag/src/main/kotlin/no/nav/bidrag/beregn/barnebidrag/service/BeregnEndeligBidragService.kt
  bidrag-beregn-barnebidrag/src/main/kotlin/no/nav/bidrag/beregn/barnebidrag/service/BeregnNettoTilsynsutgiftService.kt
  bidrag-beregn-barnebidrag/src/main/kotlin/no/nav/bidrag/beregn/barnebidrag/service/BeregnSamværsfradragService.kt
  bidrag-beregn-barnebidrag/src/test/kotlin/no/nav/bidrag/beregn/barnebidrag/BeregnSamværsklasseApiTest.kt
  bidrag-beregn-barnebidrag/src/test/kotlin/no/nav/bidrag/beregn/barnebidrag/api/BeregnBidragsevneApiTest.kt
  bidrag-beregn-barnebidrag/src/test/kotlin/no/nav/bidrag/beregn/barnebidrag/api/BeregnBpAndelUnderholdskostnadApiTest.kt
  bidrag-beregn-barnebidrag/src/test/kotlin/no/nav/bidrag/beregn/barnebidrag/api/BeregnEndeligBidragApiTest.kt
  bidrag-beregn-barnebidrag/src/test/kotlin/no/nav/bidrag/beregn/barnebidrag/api/BeregnNettoTilsynsutgiftApiTest.kt~
  bidrag-beregn-barnebidrag/src/test/kotlin/no/nav/bidrag/beregn/barnebidrag/api/BeregnSamværsfradragApiTest.kt
  bidrag-beregn-barnebidrag/src/test/resources/testfiler/bpandelunderholdskostnad/bpandel_eksempel1.json
  bidrag-beregn-barnebidrag/src/test/resources/testfiler/bpandelunderholdskostnad/bpandel_eksempel2.json
  bidrag-beregn-barnebidrag/src/test/resources/testfiler/bpandelunderholdskostnad/bpandel_eksempel3.json
  bidrag-beregn-barnebidrag/src/test/resources/testfiler/bpandelunderholdskostnad/bpandel_eksempel4.json
  bidrag-beregn-barnebidrag/src/test/resources/testfiler/bpandelunderholdskostnad/bpandel_eksempel5.json
  bidrag-beregn-barnebidrag/src/test/resources/testfiler/bpandelunderholdskostnad/bpandel_eksempel6.json
  bidrag-beregn-barnebidrag/src/test/resources/testfiler/bpandelunderholdskostnad/bpandel_eksempel_flere_perioder.json
  bidrag-beregn-barnebidrag/src/test/resources/testfiler/endeligbidrag/endeligbidrag_eksempel1.json
  bidrag-beregn-barnebidrag/src/test/resources/testfiler/endeligbidrag/endeligbidrag_eksempel2A.json
  bidrag-beregn-barnebidrag/src/test/resources/testfiler/endeligbidrag/endeligbidrag_eksempel2B.json
  bidrag-beregn-barnebidrag/src/test/resources/testfiler/endeligbidrag/endeligbidrag_eksempel3.json
  bidrag-beregn-barnebidrag/src/test/resources/testfiler/endeligbidrag/endeligbidrag_eksempel4.json
  bidrag-beregn-barnebidrag/src/test/resources/testfiler/endeligbidrag/endeligbidrag_eksempel5A.json
  bidrag-beregn-barnebidrag/src/test/resources/testfiler/endeligbidrag/endeligbidrag_eksempel5B.json
  bidrag-beregn-barnebidrag/src/test/resources/testfiler/endeligbidrag/endeligbidrag_eksempel6.json
  bidrag-beregn-barnebidrag/src/test/resources/testfiler/endeligbidrag/endeligbidrag_eksempel7.json
  bidrag-beregn-barnebidrag/src/test/resources/testfiler/endeligbidrag/endeligbidrag_eksempel8.json
  bidrag-beregn-barnebidrag/src/test/resources/testfiler/endeligbidrag/endeligbidrag_eksempel_flere_perioder.json
  bidrag-beregn-barnebidrag/src/test/resources/testfiler/nettotilsynsutgift/nettotilsynsutgift_eksempel1.json~
  bidrag-beregn-barnebidrag/src/test/resources/testfiler/nettotilsynsutgift/nettotilsynsutgift_eksempel_flere_perioder.json~
  bidrag-beregn-barnebidrag/src/test/resources/testfiler/nettotilsynsutgift/nettotilsynsutgift_flere_faktiske_utgifter_for_ett_barn.json~
  bidrag-beregn-core/src/main/kotlin/no/nav/bidrag/beregn/core/mapping/SjablonTilGrunnlagMapping.kt
  bidrag-beregn-core/src/main/kotlin/no/nav/bidrag/beregn/core/service/BeregnService.kt
  bidrag-beregn-core/src/main/kotlin/no/nav/bidrag/beregn/core/service/BeregnService.kt~
  bidrag-beregn-core/src/main/kotlin/no/nav/bidrag/beregn/core/service/mapper/CoreMapper.kt
  bidrag-beregn-core/src/main/kotlin/no/nav/bidrag/beregn/core/service/mapper/CoreMapper.kt~
  bidrag-beregn-forskudd/src/main/kotlin/no/nav/bidrag/beregn/forskudd/service/BeregnForskuddService.kt
  bidrag-beregn-særbidrag/src/main/kotlin/no/nav/bidrag/beregn/særbidrag/service/BeregnSærbidragService.kt
  bidrag-beregn-særbidrag/src/test/kotlin/no/nav/bidrag/beregn/særbidrag/api/BeregnSærbidragApiTest.kt
  pom.xml
Labels: bidrag-beregn-forskudd, bidrag-beregn-core, feature

#383 Fikse samværsfradrag sjablon mapping
  bidrag-beregn-barnebidrag/src/main/kotlin/no/nav/bidrag/beregn/barnebidrag/beregning/SamværsfradragBeregning.kt
  bidrag-beregn-core/src/main/kotlin/no/nav/bidrag/beregn/core/mapping/SjablonTilGrunnlagMapping.kt
  pom.xml
Labels: bidrag-beregn-core, feature

#384 Rettet beregning til å motta barnetillegg som årsinntekt
  bidrag-beregn-barnebidrag/src/main/kotlin/no/nav/bidrag/beregn/barnebidrag/beregning/EndeligBidragBeregning.kt
  bidrag-beregn-barnebidrag/src/test/resources/testfiler/endeligbidrag/endeligbidrag_eksempel2B.json
  bidrag-beregn-barnebidrag/src/test/resources/testfiler/endeligbidrag/endeligbidrag_eksempel3.json
  bidrag-beregn-barnebidrag/src/test/resources/testfiler/endeligbidrag/endeligbidrag_eksempel4.json
  bidrag-beregn-barnebidrag/src/test/resources/testfiler/endeligbidrag/endeligbidrag_eksempel5A.json
  bidrag-beregn-barnebidrag/src/test/resources/testfiler/endeligbidrag/endeligbidrag_eksempel5B.json
  bidrag-beregn-barnebidrag/src/test/resources/testfiler/endeligbidrag/endeligbidrag_eksempel6.json
  bidrag-beregn-barnebidrag/src/test/resources/testfiler/endeligbidrag/endeligbidrag_eksempel7.json
  bidrag-beregn-barnebidrag/src/test/resources/testfiler/endeligbidrag/endeligbidrag_eksempel8.json
  bidrag-beregn-barnebidrag/src/test/resources/testfiler/endeligbidrag/endeligbidrag_eksempel_flere_perioder.json
Labels: bugfix

#385 Åpen sluttdato på siste periode av beregninger (barnebidrag)
  bidrag-beregn-barnebidrag/src/main/kotlin/no/nav/bidrag/beregn/barnebidrag/mapper/BidragsevneMapper.kt
  bidrag-beregn-barnebidrag/src/main/kotlin/no/nav/bidrag/beregn/barnebidrag/service/BeregnBarnebidragService.kt
  bidrag-beregn-barnebidrag/src/main/kotlin/no/nav/bidrag/beregn/barnebidrag/service/BeregnBidragsevneService.kt
  bidrag-beregn-barnebidrag/src/main/kotlin/no/nav/bidrag/beregn/barnebidrag/service/BeregnBpAndelUnderholdskostnadService.kt
  bidrag-beregn-barnebidrag/src/main/kotlin/no/nav/bidrag/beregn/barnebidrag/service/BeregnEndeligBidragService.kt
  bidrag-beregn-barnebidrag/src/main/kotlin/no/nav/bidrag/beregn/barnebidrag/service/BeregnNettoTilsynsutgiftService.kt
  bidrag-beregn-barnebidrag/src/main/kotlin/no/nav/bidrag/beregn/barnebidrag/service/BeregnSamværsfradragService.kt
  bidrag-beregn-barnebidrag/src/main/kotlin/no/nav/bidrag/beregn/barnebidrag/service/BeregnUnderholdskostnadService.kt
  bidrag-beregn-barnebidrag/src/test/kotlin/no/nav/bidrag/beregn/barnebidrag/api/BeregnBarnebidragApiTest.kt
  bidrag-beregn-barnebidrag/src/test/kotlin/no/nav/bidrag/beregn/barnebidrag/api/BeregnBidragsevneApiTest.kt
  bidrag-beregn-barnebidrag/src/test/kotlin/no/nav/bidrag/beregn/barnebidrag/api/BeregnBpAndelUnderholdskostnadApiTest.kt
  bidrag-beregn-barnebidrag/src/test/kotlin/no/nav/bidrag/beregn/barnebidrag/api/BeregnEndeligBidragApiTest.kt
  bidrag-beregn-barnebidrag/src/test/kotlin/no/nav/bidrag/beregn/barnebidrag/api/BeregnNettoTilsynsutgiftApiTest.kt
  bidrag-beregn-barnebidrag/src/test/kotlin/no/nav/bidrag/beregn/barnebidrag/api/BeregnSamværsfradragApiTest.kt
  bidrag-beregn-core/src/main/kotlin/no/nav/bidrag/beregn/core/service/BeregnService.kt
  bidrag-beregn-core/src/main/kotlin/no/nav/bidrag/beregn/core/service/mapper/CoreMapper.kt
Labels: bidrag-beregn-core, feature

#387 Tilpasse endringer SluttberegningBarnebidrag
  bidrag-beregn-barnebidrag/src/main/kotlin/no/nav/bidrag/beregn/barnebidrag/mapper/NettoTilsynsutgiftMapper.kt
  bidrag-beregn-barnebidrag/src/main/kotlin/no/nav/bidrag/beregn/barnebidrag/service/BeregnBarnebidragService.kt
  bidrag-beregn-barnebidrag/src/main/kotlin/no/nav/bidrag/beregn/barnebidrag/service/BeregnEndeligBidragService.kt
  bidrag-beregn-barnebidrag/src/test/kotlin/no/nav/bidrag/beregn/barnebidrag/api/BeregnBarnebidragApiTest.kt
  bidrag-beregn-barnebidrag/src/test/kotlin/no/nav/bidrag/beregn/barnebidrag/api/BeregnEndeligBidragApiTest.kt
  bidrag-beregn-barnebidrag/src/test/resources/testfiler/nettotilsynsutgift/nettotilsynsutgift_eksempel1.json
  bidrag-beregn-barnebidrag/src/test/resources/testfiler/nettotilsynsutgift/nettotilsynsutgift_eksempel_flere_perioder.json
  bidrag-beregn-barnebidrag/src/test/resources/testfiler/nettotilsynsutgift/nettotilsynsutgift_eksempel_over_sjablon_maks_tilsyn_flere_barn.json
  bidrag-beregn-barnebidrag/src/test/resources/testfiler/nettotilsynsutgift/nettotilsynsutgift_flere_faktiske_utgifter_for_ett_barn.json
  pom.xml
Labels: feature

#389 Feilfiks properties i pom
  bidrag-beregn-core/src/main/kotlin/no/nav/bidrag/beregn/core/service/BeregnService.kt
  bidrag-beregn-core/src/main/kotlin/no/nav/bidrag/beregn/core/util/SjablonUtil.kt
  pom.xml
Labels: bidrag-beregn-core, bugfix

#395 Endret beregnmetoden til å ta med resultatet av netto tilsynsutgift i…
  bidrag-beregn-barnebidrag/src/main/kotlin/no/nav/bidrag/beregn/barnebidrag/service/BeregnBarnebidragService.kt
  bidrag-beregn-barnebidrag/src/main/kotlin/no/nav/bidrag/beregn/barnebidrag/service/BeregnBarnebidragService.kt~
Labels: feature

#406 Bruke gjelderbarnreferanse i beregning av bidrag
  bidrag-beregn-barnebidrag/src/main/kotlin/no/nav/bidrag/beregn/barnebidrag/mapper/NettoTilsynsutgiftMapper.kt
  bidrag-beregn-barnebidrag/src/main/kotlin/no/nav/bidrag/beregn/barnebidrag/service/BeregnBidragsevneService.kt
  bidrag-beregn-barnebidrag/src/main/kotlin/no/nav/bidrag/beregn/barnebidrag/service/BeregnBpAndelUnderholdskostnadService.kt
  bidrag-beregn-barnebidrag/src/main/kotlin/no/nav/bidrag/beregn/barnebidrag/service/BeregnEndeligBidragService.kt
  bidrag-beregn-barnebidrag/src/main/kotlin/no/nav/bidrag/beregn/barnebidrag/service/BeregnNettoTilsynsutgiftService.kt
  bidrag-beregn-barnebidrag/src/main/kotlin/no/nav/bidrag/beregn/barnebidrag/service/BeregnSamværsfradragService.kt
  bidrag-beregn-barnebidrag/src/main/kotlin/no/nav/bidrag/beregn/barnebidrag/service/BeregnUnderholdskostnadService.kt
  bidrag-beregn-barnebidrag/src/test/resources/testfiler/nettobarnetilsynogunderholdskostnad/nettotilsynsutgift_og_underholdskostnad_enkel_test.json
  bidrag-beregn-barnebidrag/src/test/resources/testfiler/nettobarnetilsynogunderholdskostnad/nettotilsynsutgift_og_underholdskostnad_flere_perioder.json
  bidrag-beregn-barnebidrag/src/test/resources/testfiler/nettobarnetilsynogunderholdskostnad/nettotilsynsutgift_og_underholdskostnad_full_request.json
  bidrag-beregn-barnebidrag/src/test/resources/testfiler/nettotilsynsutgift/nettotilsynsutgift_eksempel1.json
  bidrag-beregn-barnebidrag/src/test/resources/testfiler/nettotilsynsutgift/nettotilsynsutgift_eksempel2_kun_faktiske_utgifter.json
  bidrag-beregn-barnebidrag/src/test/resources/testfiler/nettotilsynsutgift/nettotilsynsutgift_eksempel3_utregning_tilleggsstønad.json
  bidrag-beregn-barnebidrag/src/test/resources/testfiler/nettotilsynsutgift/nettotilsynsutgift_eksempel_flere_perioder.json
  bidrag-beregn-barnebidrag/src/test/resources/testfiler/nettotilsynsutgift/nettotilsynsutgift_eksempel_over_sjablon_maks_tilsyn_flere_barn.json
  bidrag-beregn-barnebidrag/src/test/resources/testfiler/nettotilsynsutgift/nettotilsynsutgift_flere_faktiske_utgifter_for_ett_barn.json
  bidrag-beregn-forskudd/src/main/kotlin/no/nav/bidrag/beregn/forskudd/service/BeregnForskuddService.kt
  bidrag-beregn-særbidrag/src/main/kotlin/no/nav/bidrag/beregn/særbidrag/service/BeregnSærbidragService.kt
  pom.xml
Labels: bidrag-beregn-forskudd, feature

#409 Legg til gjelderReferanse og gjelderBarnReferanse i samværgrunnlag
  bidrag-beregn-barnebidrag/src/main/kotlin/no/nav/bidrag/beregn/barnebidrag/BeregnSamværsklasseApi.kt
  pom.xml
Labels: feature

#410 Fjernet bortfiltrering av barn fra 13 år og oppover. Netto tilsynsutgift
  bidrag-beregn-barnebidrag/src/main/kotlin/no/nav/bidrag/beregn/barnebidrag/beregning/EndeligBidragBeregning.kt
  bidrag-beregn-barnebidrag/src/main/kotlin/no/nav/bidrag/beregn/barnebidrag/beregning/NettoTilsynsutgiftBeregning.kt
  bidrag-beregn-barnebidrag/src/main/kotlin/no/nav/bidrag/beregn/barnebidrag/beregning/NettoTilsynsutgiftBeregning.kt~
  bidrag-beregn-barnebidrag/src/main/kotlin/no/nav/bidrag/beregn/barnebidrag/bo/EndeligBidragBO.kt
  bidrag-beregn-barnebidrag/src/main/kotlin/no/nav/bidrag/beregn/barnebidrag/service/BeregnNettoTilsynsutgiftService.kt
Labels: feature

#415 Ny api for beregning av gebyr
  bidrag-beregn-barnebidrag/src/main/kotlin/no/nav/bidrag/beregn/barnebidrag/BeregnGebyrApi.kt
  bidrag-beregn-barnebidrag/src/main/kotlin/no/nav/bidrag/beregn/barnebidrag/BeregnSamværsklasseApi.kt
  bidrag-beregn-barnebidrag/src/main/kotlin/no/nav/bidrag/beregn/barnebidrag/beregning/BeregnGebyrService.kt
  bidrag-beregn-barnebidrag/src/test/kotlin/no/nav/bidrag/beregn/barnebidrag/BeregnSamværsklasseApiTest.kt
  bidrag-beregn-barnebidrag/src/test/kotlin/no/nav/bidrag/beregn/barnebidrag/beregning/GebyrBeregningApiTest.kt
  bidrag-beregn-core/src/main/kotlin/no/nav/bidrag/beregn/core/mapping/SjablonTilGrunnlagMapping.kt
  pom.xml
Labels: bidrag-beregn-core, feature

#417 Feilfiks referanser i gebyr
  bidrag-beregn-barnebidrag/src/main/kotlin/no/nav/bidrag/beregn/barnebidrag/beregning/BeregnGebyrService.kt
  bidrag-beregn-barnebidrag/src/test/kotlin/no/nav/bidrag/beregn/barnebidrag/beregning/GebyrBeregningApiTest.kt
Labels: feature
