Repository navikt/bidrag-beregn-felles, pull requests merged in 2024-10, with the labels that each got.

#319 Ikke legg til grunnlag delberegning utgift i sluttberegning
  bidrag-beregn-særbidrag/src/main/kotlin/no/nav/bidrag/beregn/særbidrag/core/særbidrag/SærbidragCore.kt
Labels: bugfix

#320 Oppgrader bidrag-felles
  pom.xml
Labels: chore

#321 Feature/særbidrag/bidragsevne bpsandel output
  bidrag-beregn-core/src/main/kotlin/no/nav/bidrag/beregn/core/service/BeregnService.kt
  bidrag-beregn-særbidrag/src/main/kotlin/no/nav/bidrag/beregn/særbidrag/core/bidragsevne/BidragsevneCore.kt
  bidrag-beregn-særbidrag/src/main/kotlin/no/nav/bidrag/beregn/særbidrag/core/bidragsevne/beregning/BidragsevneBeregning.kt
  bidrag-beregn-særbidrag/src/main/kotlin/no/nav/bidrag/beregn/særbidrag/core/bidragsevne/bo/CoreBO.kt
  bidrag-beregn-særbidrag/src/main/kotlin/no/nav/bidrag/beregn/særbidrag/core/bidragsevne/dto/CoreDTO.kt
  bidrag-beregn-særbidrag/src/main/kotlin/no/nav/bidrag/beregn/særbidrag/core/bpsandelsærbidrag/BPsAndelSærbidragCore.kt
  bidrag-beregn-særbidrag/src/main/kotlin/no/nav/bidrag/beregn/særbidrag/core/bpsandelsærbidrag/beregning/BPsAndelSærbidragBeregning.kt
  bidrag-beregn-særbidrag/src/main/kotlin/no/nav/bidrag/beregn/særbidrag/core/bpsandelsærbidrag/bo/CoreBO.kt
  bidrag-beregn-særbidrag/src/main/kotlin/no/nav/bidrag/beregn/særbidrag/core/bpsandelsærbidrag/dto/CoreDTO.kt
  bidrag-beregn-særbidrag/src/main/kotlin/no/nav/bidrag/beregn/særbidrag/core/sumløpendebidrag/beregning/SumLøpendeBidragBeregning.kt
  bidrag-beregn-særbidrag/src/main/kotlin/no/nav/bidrag/beregn/særbidrag/core/særbidrag/SærbidragCore.kt
  bidrag-beregn-særbidrag/src/main/kotlin/no/nav/bidrag/beregn/særbidrag/core/særbidrag/bo/CoreBO.kt
  bidrag-beregn-særbidrag/src/main/kotlin/no/nav/bidrag/beregn/særbidrag/core/særbidrag/bo/Periode.kt
  bidrag-beregn-særbidrag/src/main/kotlin/no/nav/bidrag/beregn/særbidrag/core/særbidrag/dto/CoreDTO.kt
  bidrag-beregn-særbidrag/src/main/kotlin/no/nav/bidrag/beregn/særbidrag/core/særbidrag/periode/SærbidragPeriode.kt
  bidrag-beregn-særbidrag/src/main/kotlin/no/nav/bidrag/beregn/særbidrag/service/BeregnSærbidragService.kt
  bidrag-beregn-særbidrag/src/main/kotlin/no/nav/bidrag/beregn/særbidrag/service/mapper/SærbidragCoreMapper.kt
  bidrag-beregn-særbidrag/src/test/kotlin/no/nav/bidrag/beregn/særbidrag/TestUtil.kt
  bidrag-beregn-særbidrag/src/test/kotlin/no/nav/bidrag/beregn/særbidrag/api/BeregnSærbidragApiTest.kt
  bidrag-beregn-særbidrag/src/test/kotlin/no/nav/bidrag/beregn/særbidrag/core/bidragsevne/BidragsevneCoreTest.kt
  bidrag-beregn-særbidrag/src/test/kotlin/no/nav/bidrag/beregn/særbidrag/core/bidragsevne/BidragsevnePeriodeTest.kt
  bidrag-beregn-særbidrag/src/test/kotlin/no/nav/bidrag/beregn/særbidrag/core/bpsandelsærbidrag/BPsAndelSærbidragBeregningTest.kt
  bidrag-beregn-særbidrag/src/test/kotlin/no/nav/bidrag/beregn/særbidrag/core/bpsandelsærbidrag/BPsAndelSærbidragCoreTest.kt
  bidrag-beregn-særbidrag/src/test/kotlin/no/nav/bidrag/beregn/særbidrag/core/bpsandelsærbidrag/BPsAndelSærbidragPeriodeTest.kt
  bidrag-beregn-særbidrag/src/test/kotlin/no/nav/bidrag/beregn/særbidrag/core/særbidrag/SærbidragBeregningTest.kt
  bidrag-beregn-særbidrag/src/test/kotlin/no/nav/bidrag/beregn/særbidrag/core/særbidrag/SærbidragCoreTest.kt
  bidrag-beregn-særbidrag/src/test/kotlin/no/nav/bidrag/beregn/særbidrag/core/særbidrag/SærbidragPeriodeTest.kt
  pom.xml
Labels: bidrag-beregn-core, feature

#322 Legger ut sumpost for ainntekt opprinnelig vedtaksdato også hvis sum …
  bidrag-inntekt/src/main/kotlin/no/nav/bidrag/inntekt/service/AinntektService.kt
Labels: bidrag-inntekt, feature

#329 Hent siste sjablonsats for FORSKUDDSSATS_BELØP
  bidrag-beregn-særbidrag/src/main/kotlin/no/nav/bidrag/beregn/særbidrag/service/BeregnSærbidragService.kt
Labels: feature

#331 Lagt til avrunding beregnetBeløp i sumLøpendeBidrag pluss tjeneste fo…
  bidrag-beregn-særbidrag/src/main/kotlin/no/nav/bidrag/beregn/særbidrag/ValiderSærbidragForBeregningService.kt
  bidrag-beregn-særbidrag/src/main/kotlin/no/nav/bidrag/beregn/særbidrag/core/sumløpendebidrag/beregning/SumLøpendeBidragBeregning.kt
  bidrag-beregn-særbidrag/src/main/kotlin/no/nav/bidrag/beregn/særbidrag/service/BeregnSærbidragService.kt
  bidrag-beregn-særbidrag/src/test/kotlin/no/nav/bidrag/beregn/særbidrag/core/sumløpendebidrag/SumLøpendeBidragBeregningTest.kt
Labels: feature

#339 Endringer evnevurdering særbidrag
  bidrag-beregn-core/src/main/kotlin/no/nav/bidrag/beregn/core/service/BeregnService.kt
  bidrag-beregn-særbidrag/src/main/kotlin/no/nav/bidrag/beregn/særbidrag/core/bpsberegnedetotalbidrag/BPsBeregnedeTotalbidragCore.kt
  bidrag-beregn-særbidrag/src/main/kotlin/no/nav/bidrag/beregn/særbidrag/core/bpsberegnedetotalbidrag/beregning/BPsBeregnedeTotalbidragBeregning.kt
  bidrag-beregn-særbidrag/src/main/kotlin/no/nav/bidrag/beregn/særbidrag/core/bpsberegnedetotalbidrag/bo/CoreBO.kt
  bidrag-beregn-særbidrag/src/main/kotlin/no/nav/bidrag/beregn/særbidrag/core/bpsberegnedetotalbidrag/dto/CoreDTO.kt
  bidrag-beregn-særbidrag/src/main/kotlin/no/nav/bidrag/beregn/særbidrag/core/bpsberegnedetotalbidrag/periode/BPsBeregnedeTotalbidragPeriode.kt
  bidrag-beregn-særbidrag/src/main/kotlin/no/nav/bidrag/beregn/særbidrag/core/sumløpendebidrag/SumLøpendeBidragCore.kt
  bidrag-beregn-særbidrag/src/main/kotlin/no/nav/bidrag/beregn/særbidrag/core/sumløpendebidrag/bo/CoreBO.kt
  bidrag-beregn-særbidrag/src/main/kotlin/no/nav/bidrag/beregn/særbidrag/core/sumløpendebidrag/periode/SumLøpendeBidragPeriode.kt
  bidrag-beregn-særbidrag/src/main/kotlin/no/nav/bidrag/beregn/særbidrag/core/særbidrag/SærbidragCore.kt
  bidrag-beregn-særbidrag/src/main/kotlin/no/nav/bidrag/beregn/særbidrag/core/særbidrag/beregning/SærbidragBeregning.kt
  bidrag-beregn-særbidrag/src/main/kotlin/no/nav/bidrag/beregn/særbidrag/core/særbidrag/bo/CoreBO.kt
  bidrag-beregn-særbidrag/src/main/kotlin/no/nav/bidrag/beregn/særbidrag/core/særbidrag/bo/Periode.kt
  bidrag-beregn-særbidrag/src/main/kotlin/no/nav/bidrag/beregn/særbidrag/core/særbidrag/dto/CoreDTO.kt
  bidrag-beregn-særbidrag/src/main/kotlin/no/nav/bidrag/beregn/særbidrag/core/særbidrag/periode/SærbidragPeriode.kt
  bidrag-beregn-særbidrag/src/main/kotlin/no/nav/bidrag/beregn/særbidrag/service/BeregnSærbidragService.kt
  bidrag-beregn-særbidrag/src/main/kotlin/no/nav/bidrag/beregn/særbidrag/service/mapper/BPsBeregnedeTotalbidragCoreMapper.kt
  bidrag-beregn-særbidrag/src/main/kotlin/no/nav/bidrag/beregn/særbidrag/service/mapper/SumLøpendeBidragCoreMapper.kt~
  bidrag-beregn-særbidrag/src/main/kotlin/no/nav/bidrag/beregn/særbidrag/service/mapper/SærbidragCoreMapper.kt
  bidrag-beregn-særbidrag/src/test/kotlin/no/nav/bidrag/beregn/særbidrag/TestUtil.kt
  bidrag-beregn-særbidrag/src/test/kotlin/no/nav/bidrag/beregn/særbidrag/api/BeregnSærbidragApiTest.kt
  bidrag-beregn-særbidrag/src/test/kotlin/no/nav/bidrag/beregn/særbidrag/core/bpsberegnedetotalbidrag/BPsBeregnedeTotalbidragBeregningTest.kt
  bidrag-beregn-særbidrag/src/test/kotlin/no/nav/bidrag/beregn/særbidrag/core/særbidrag/SærbidragBeregningTest.kt
  bidrag-beregn-særbidrag/src/test/kotlin/no/nav/bidrag/beregn/særbidrag/core/særbidrag/SærbidragCoreTest.kt~
  bidrag-beregn-særbidrag/src/test/kotlin/no/nav/bidrag/beregn/særbidrag/core/særbidrag/SærbidragPeriodeTest.kt
  bidrag-beregn-særbidrag/src/test/kotlin/no/nav/bidrag/beregn/særbidrag/service/BeregnSærbidragServiceTest.kt
  bidrag-beregn-særbidrag/src/test/resources/testfiler/særbidrag_eksempel_reduksjon_underholdskostnad_overstyres_til_0.json
  pom.xml
Labels: bidrag-beregn-core, feature

#347 Ikke filtrer ut delberegning uten inntekter
  bidrag-beregn-core/src/main/kotlin/no/nav/bidrag/beregn/core/service/BeregnService.kt
Labels: bidrag-beregn-core, bugfix

#348 Feature/sum inntekt delberegning
  bidrag-beregn-barnebidrag/src/main/kotlin/no/nav/bidrag/beregn/barnebidrag/bo/BpAndelUnderholdskostnadBO.kt
  bidrag-beregn-barnebidrag/src/main/kotlin/no/nav/bidrag/beregn/barnebidrag/service/BeregnBidragsevneService.kt
  bidrag-beregn-barnebidrag/src/main/kotlin/no/nav/bidrag/beregn/barnebidrag/service/BeregnBpAndelUnderholdskostnadService.kt
  bidrag-beregn-barnebidrag/src/test/kotlin/no/nav/bidrag/beregn/barnebidrag/api/BeregnBidragsevneApiTest.kt
  bidrag-beregn-barnebidrag/src/test/kotlin/no/nav/bidrag/beregn/barnebidrag/api/BeregnBpAndelUnderholdskostnadApiTest.kt
  bidrag-beregn-barnebidrag/src/test/kotlin/no/nav/bidrag/beregn/barnebidrag/api/BeregnSamværsfradragApiTest.kt
  bidrag-beregn-barnebidrag/src/test/resources/testfiler/bidragsevne/bidragsevne_eksempel19.json
  bidrag-beregn-barnebidrag/src/test/resources/testfiler/bpandelunderholdskostnad/bpandel_eksempel6.json
  bidrag-beregn-barnebidrag/src/test/resources/testfiler/bpandelunderholdskostnad/bpandel_eksempel7.json
  bidrag-beregn-barnebidrag/src/test/resources/testfiler/samværsfradrag/samværsfradrag_eksempel1.json
  bidrag-beregn-core/src/main/kotlin/no/nav/bidrag/beregn/core/service/BeregnService.kt
  bidrag-beregn-core/src/main/kotlin/no/nav/bidrag/beregn/core/service/mapper/CoreMapper.kt
  bidrag-beregn-særbidrag/src/test/kotlin/no/nav/bidrag/beregn/særbidrag/api/BeregnSærbidragApiTest.kt
Labels: bidrag-beregn-core, feature

#349 Endre vedtaksfiltrering
  bidrag-vedtak/src/main/kotlin/no/nav/bidrag/beregn/vedtak/Filtrering.kt
  bidrag-vedtak/src/main/kotlin/no/nav/bidrag/beregn/vedtak/Utvidelser.kt
  bidrag-vedtak/src/test/kotlin/no/nav/bidrag/beregn/vedtak/VedtaksfiltreringTest.kt
Labels: bugfix

#350 Lagt til desimaler i output fra delberegninger (beløp 2 desimaler, pr…
  bidrag-beregn-barnebidrag/src/main/kotlin/no/nav/bidrag/beregn/barnebidrag/beregning/BidragsevneBeregning.kt
  bidrag-beregn-barnebidrag/src/main/kotlin/no/nav/bidrag/beregn/barnebidrag/beregning/BpAndelUnderholdskostnadBeregning.kt
  bidrag-beregn-barnebidrag/src/main/kotlin/no/nav/bidrag/beregn/barnebidrag/beregning/SamværsfradragBeregning.kt
  bidrag-beregn-barnebidrag/src/test/kotlin/no/nav/bidrag/beregn/barnebidrag/api/BeregnBidragsevneApiTest.kt
  bidrag-beregn-barnebidrag/src/test/kotlin/no/nav/bidrag/beregn/barnebidrag/api/BeregnBpAndelUnderholdskostnadApiTest.kt
  bidrag-beregn-barnebidrag/src/test/kotlin/no/nav/bidrag/beregn/barnebidrag/api/BeregnSamværsfradragApiTest.kt
  bidrag-beregn-core/src/main/kotlin/no/nav/bidrag/beregn/core/service/BeregnService.kt
  bidrag-beregn-core/src/main/kotlin/no/nav/bidrag/beregn/core/service/mapper/CoreMapper.kt
  bidrag-beregn-forskudd/src/test/kotlin/no/nav/bidrag/beregn/forskudd/service/ForskuddCoreMapperTest.kt
  bidrag-beregn-særbidrag/src/main/kotlin/no/nav/bidrag/beregn/særbidrag/core/bidragsevne/beregning/BidragsevneBeregning.kt
  bidrag-beregn-særbidrag/src/main/kotlin/no/nav/bidrag/beregn/særbidrag/core/bpsandelsærbidrag/beregning/BPsAndelSærbidragBeregning.kt
  bidrag-beregn-særbidrag/src/main/kotlin/no/nav/bidrag/beregn/særbidrag/core/bpsberegnedetotalbidrag/beregning/BPsBeregnedeTotalbidragBeregning.kt
  bidrag-beregn-særbidrag/src/main/kotlin/no/nav/bidrag/beregn/særbidrag/core/særbidrag/beregning/SærbidragBeregning.kt
  bidrag-beregn-særbidrag/src/test/kotlin/no/nav/bidrag/beregn/særbidrag/api/BeregnSærbidragApiTest.kt
  bidrag-beregn-særbidrag/src/test/kotlin/no/nav/bidrag/beregn/særbidrag/core/bidragsevne/BidragsevneBeregningTest.kt
  bidrag-beregn-særbidrag/src/test/kotlin/no/nav/bidrag/beregn/særbidrag/core/bpsandelsærbidrag/BPsAndelSærbidragBeregningTest.kt
  bidrag-beregn-særbidrag/src/test/kotlin/no/nav/bidrag/beregn/særbidrag/core/bpsberegnedetotalbidrag/BPsBeregnedeTotalbidragBeregningTest.kt
  bidrag-beregn-særbidrag/src/test/kotlin/no/nav/bidrag/beregn/særbidrag/core/særbidrag/SærbidragBeregningTest.kt
Labels: bidrag-beregn-forskudd, bidrag-beregn-core, feature

#351 Lagt til ny delberegning boforhold under bidragsevne-beregning
  bidrag-beregn-barnebidrag/src/main/kotlin/no/nav/bidrag/beregn/barnebidrag/bo/BidragsevneBO.kt
  bidrag-beregn-barnebidrag/src/main/kotlin/no/nav/bidrag/beregn/barnebidrag/mapper/BidragsevneMapper.kt
  bidrag-beregn-barnebidrag/src/main/kotlin/no/nav/bidrag/beregn/barnebidrag/service/BeregnBidragsevneService.kt
  bidrag-beregn-barnebidrag/src/test/kotlin/no/nav/bidrag/beregn/barnebidrag/api/BeregnBidragsevneApiTest.kt
  bidrag-beregn-core/src/main/kotlin/no/nav/bidrag/beregn/core/dto/CoreDto.kt
  bidrag-beregn-core/src/main/kotlin/no/nav/bidrag/beregn/core/service/BeregnService.kt
  bidrag-beregn-core/src/main/kotlin/no/nav/bidrag/beregn/core/service/mapper/CoreMapper.kt
  bidrag-beregn-særbidrag/src/main/kotlin/no/nav/bidrag/beregn/særbidrag/core/bidragsevne/BidragsevneCore.kt
  bidrag-beregn-særbidrag/src/main/kotlin/no/nav/bidrag/beregn/særbidrag/core/bidragsevne/dto/CoreDTO.kt
  bidrag-beregn-særbidrag/src/main/kotlin/no/nav/bidrag/beregn/særbidrag/service/BeregnSærbidragService.kt
  bidrag-beregn-særbidrag/src/main/kotlin/no/nav/bidrag/beregn/særbidrag/service/mapper/BidragsevneCoreMapper.kt
  bidrag-beregn-særbidrag/src/test/kotlin/no/nav/bidrag/beregn/særbidrag/TestUtil.kt
  bidrag-beregn-særbidrag/src/test/kotlin/no/nav/bidrag/beregn/særbidrag/api/BeregnSærbidragApiTest.kt
  bidrag-beregn-særbidrag/src/test/kotlin/no/nav/bidrag/beregn/særbidrag/core/bidragsevne/BidragsevneCoreTest.kt
  pom.xml
Labels: bidrag-beregn-core, feature

#353 Tatt i bruk felles-funksjoner for avrunding/presisjon på BigDecimal
  bidrag-beregn-barnebidrag/src/main/kotlin/no/nav/bidrag/beregn/barnebidrag/beregning/BidragsevneBeregning.kt
  bidrag-beregn-barnebidrag/src/main/kotlin/no/nav/bidrag/beregn/barnebidrag/beregning/BpAndelUnderholdskostnadBeregning.kt
  bidrag-beregn-barnebidrag/src/main/kotlin/no/nav/bidrag/beregn/barnebidrag/beregning/SamværsfradragBeregning.kt
  bidrag-beregn-barnebidrag/src/test/kotlin/no/nav/bidrag/beregn/barnebidrag/api/BeregnBidragsevneApiTest.kt
  bidrag-beregn-barnebidrag/src/test/kotlin/no/nav/bidrag/beregn/barnebidrag/api/BeregnBpAndelUnderholdskostnadApiTest.kt
  bidrag-beregn-særbidrag/src/main/kotlin/no/nav/bidrag/beregn/særbidrag/core/bidragsevne/beregning/BidragsevneBeregning.kt
  bidrag-beregn-særbidrag/src/main/kotlin/no/nav/bidrag/beregn/særbidrag/core/bpsandelsærbidrag/beregning/BPsAndelSærbidragBeregning.kt
  bidrag-beregn-særbidrag/src/main/kotlin/no/nav/bidrag/beregn/særbidrag/core/bpsberegnedetotalbidrag/beregning/BPsBeregnedeTotalbidragBeregning.kt
  bidrag-beregn-særbidrag/src/main/kotlin/no/nav/bidrag/beregn/særbidrag/core/særbidrag/beregning/SærbidragBeregning.kt
Labels: feature

#358 Apo for beregning av samværsklasse
  bidrag-beregn-barnebidrag/pom.xml
  bidrag-beregn-barnebidrag/src/main/kotlin/no/nav/bidrag/beregn/barnebidrag/BeregnSamværsklasseApi.kt
  bidrag-beregn-barnebidrag/src/test/kotlin/no/nav/bidrag/beregn/barnebidrag/BeregnSamværsklasseApiTest.kt
  bidrag-beregn-core/src/main/kotlin/no/nav/bidrag/beregn/core/util/BeregningUtil.kt
  bidrag-beregn-særbidrag/src/main/kotlin/no/nav/bidrag/beregn/særbidrag/core/særbidrag/beregning/SærbidragBeregning.kt
Labels: bidrag-beregn-core, feature

#359 Oppdatere api for beregning av samværsklasse
  bidrag-beregn-barnebidrag/src/main/kotlin/no/nav/bidrag/beregn/barnebidrag/BeregnSamværsklasseApi.kt
Labels: bugfix

#360 Vedtaksfiltrering - fjerne pre-filtrering av indeksregulerte vedtak
  bidrag-vedtak/src/main/kotlin/no/nav/bidrag/beregn/vedtak/Filtrering.kt
  bidrag-vedtak/src/main/kotlin/no/nav/bidrag/beregn/vedtak/Utvidelser.kt
Labels: bugfix

#361 Vedtak filtrering ikke kast feil hvis ikke funnet vedtak
  bidrag-vedtak/src/main/kotlin/no/nav/bidrag/beregn/vedtak/Filtrering.kt
Labels: bugfix

#362 Fikset feil i samværsberegning
  bidrag-beregn-barnebidrag/src/main/kotlin/no/nav/bidrag/beregn/barnebidrag/BeregnSamværsklasseApi.kt
  bidrag-beregn-barnebidrag/src/test/kotlin/no/nav/bidrag/beregn/barnebidrag/BeregnSamværsklasseApiTest.kt
  pom.xml
Labels: bugfix
