Repository navikt/bidrag-beregn-felles, pull requests merged in 2025-03, with the labels that each got.

#511 Privat avtale skal hensyntas i 12%-beregning hvis det ikke finnes bel…
  bidrag-beregn-barnebidrag/src/main/kotlin/no/nav/bidrag/beregn/barnebidrag/beregning/EndringSjekkGrensePeriodeBeregning.kt
  bidrag-beregn-barnebidrag/src/main/kotlin/no/nav/bidrag/beregn/barnebidrag/bo/EndringSjekkGrenseBO.kt
  bidrag-beregn-barnebidrag/src/main/kotlin/no/nav/bidrag/beregn/barnebidrag/bo/EndringSjekkGrensePeriodeBO.kt
  bidrag-beregn-barnebidrag/src/main/kotlin/no/nav/bidrag/beregn/barnebidrag/mapper/EndringSjekkGrensePeriodeMapper.kt
  bidrag-beregn-barnebidrag/src/main/kotlin/no/nav/bidrag/beregn/barnebidrag/service/BeregnBarnebidragService.kt
  bidrag-beregn-barnebidrag/src/main/kotlin/no/nav/bidrag/beregn/barnebidrag/service/BeregnEndringSjekkGrensePeriodeService.kt
  bidrag-beregn-barnebidrag/src/main/kotlin/no/nav/bidrag/beregn/barnebidrag/service/BeregnIndeksreguleringPrivatAvtaleService.kt
  bidrag-beregn-barnebidrag/src/test/kotlin/no/nav/bidrag/beregn/barnebidrag/api/BeregnBarnebidragApiTest.kt
  bidrag-beregn-barnebidrag/src/test/resources/testfiler/barnebidrag/barnebidrag_eksempel8A.json
  bidrag-beregn-barnebidrag/src/test/resources/testfiler/barnebidrag/barnebidrag_eksempel8B.json
  bidrag-beregn-barnebidrag/src/test/resources/testfiler/barnebidrag/barnebidrag_eksempel8C.json
  bidrag-beregn-barnebidrag/src/test/resources/testfiler/barnebidrag/barnebidrag_eksempel8D.json
  bidrag-beregn-barnebidrag/src/test/resources/testfiler/barnebidrag/barnebidrag_eksempel8E.json
Labels: feature

#512 Fjernet sjablonreferanse fra resultatperiode
  bidrag-beregn-barnebidrag/src/main/kotlin/no/nav/bidrag/beregn/barnebidrag/service/BeregnBarnebidragService.kt
Labels: bugfix

#515 Refaktorering opphørsdato ikke sett opphørsdato på delberegninger
  bidrag-beregn-barnebidrag/src/main/kotlin/no/nav/bidrag/beregn/barnebidrag/service/BeregnBarnetilleggSkattesatsService.kt
  bidrag-beregn-barnebidrag/src/main/kotlin/no/nav/bidrag/beregn/barnebidrag/service/BeregnBidragsevneService.kt
  bidrag-beregn-barnebidrag/src/main/kotlin/no/nav/bidrag/beregn/barnebidrag/service/BeregnBpAndelUnderholdskostnadService.kt
  bidrag-beregn-barnebidrag/src/main/kotlin/no/nav/bidrag/beregn/barnebidrag/service/BeregnEndeligBidragService.kt
  bidrag-beregn-barnebidrag/src/main/kotlin/no/nav/bidrag/beregn/barnebidrag/service/BeregnEndringSjekkGrensePeriodeService.kt
  bidrag-beregn-barnebidrag/src/main/kotlin/no/nav/bidrag/beregn/barnebidrag/service/BeregnSamværsfradragService.kt
  bidrag-beregn-barnebidrag/src/main/kotlin/no/nav/bidrag/beregn/barnebidrag/service/BeregnUnderholdskostnadService.kt
  bidrag-beregn-barnebidrag/src/test/kotlin/no/nav/bidrag/beregn/barnebidrag/api/BeregnBarnebidragApiTest.kt
  bidrag-beregn-barnebidrag/src/test/kotlin/no/nav/bidrag/beregn/barnebidrag/api/FellesApiTest.kt
  bidrag-beregn-barnebidrag/src/test/kotlin/no/nav/bidrag/beregn/barnebidrag/api/TestData.kt
  bidrag-beregn-core/src/main/kotlin/no/nav/bidrag/beregn/core/service/mapper/CoreMapper.kt
Labels: bidrag-beregn-core, feature

#518 Oppdater bidrag-felles
  pom.xml
Labels: feature

#520 18-åringer skal ikke ha barnetrygd ved beregning av U
  bidrag-beregn-barnebidrag/src/main/kotlin/no/nav/bidrag/beregn/barnebidrag/service/BeregnUnderholdskostnadService.kt
Labels: feature

#522 Barnetrygd skal ikke hensyntas ved beregning av U på 18-års-bidrag
  bidrag-beregn-barnebidrag/src/main/kotlin/no/nav/bidrag/beregn/barnebidrag/service/BeregnBarnebidragService.kt
Labels: bugfix

#523 Hvis barnet er selvforsørget skal beregnet beløp være null
  bidrag-beregn-barnebidrag/src/main/kotlin/no/nav/bidrag/beregn/barnebidrag/beregning/EndeligBidragBeregning.kt
  bidrag-beregn-barnebidrag/src/main/kotlin/no/nav/bidrag/beregn/barnebidrag/service/BeregnBarnebidragService.kt
  bidrag-beregn-barnebidrag/src/test/kotlin/no/nav/bidrag/beregn/barnebidrag/api/BeregnEndeligBidragApiTest.kt
  pom.xml
Labels: bugfix

#526 feature/filter_siste_manuelle
  bidrag-vedtak/src/main/kotlin/no/nav/bidrag/beregn/vedtak/Felles.kt
  bidrag-vedtak/src/main/kotlin/no/nav/bidrag/beregn/vedtak/Vedtaksfiltrering.kt
  pom.xml
Labels: feature

#531 Justert litt på logikken for beregning av over/under grense
  bidrag-beregn-barnebidrag/src/main/kotlin/no/nav/bidrag/beregn/barnebidrag/beregning/EndringSjekkGrenseBeregning.kt
  bidrag-beregn-barnebidrag/src/main/kotlin/no/nav/bidrag/beregn/barnebidrag/beregning/EndringSjekkGrensePeriodeBeregning.kt
  bidrag-beregn-barnebidrag/src/test/kotlin/no/nav/bidrag/beregn/barnebidrag/api/BeregnEndringSjekkGrensePeriodeApiTest.kt
  bidrag-beregn-barnebidrag/src/test/resources/testfiler/endringsjekkgrense/endring_sjekk_grense_eksempel3.json
Labels: bugfix

#532 feature/aldersjustering_beregning_v1
  bidrag-beregn-barnebidrag/pom.xml
  bidrag-beregn-barnebidrag/src/main/kotlin/no/nav/bidrag/beregn/barnebidrag/service/AldersjusteringOrchestrator.kt
  bidrag-beregn-barnebidrag/src/main/kotlin/no/nav/bidrag/beregn/barnebidrag/service/VedtakService.kt
  bidrag-beregn-barnebidrag/src/main/kotlin/no/nav/bidrag/beregn/barnebidrag/service/external/BeregningPersonConsumer.kt
  bidrag-beregn-barnebidrag/src/main/kotlin/no/nav/bidrag/beregn/barnebidrag/service/external/BeregningSakConsumer.kt
  bidrag-beregn-barnebidrag/src/main/kotlin/no/nav/bidrag/beregn/barnebidrag/service/external/BeregningStønadConsumer.kt
  bidrag-beregn-barnebidrag/src/main/kotlin/no/nav/bidrag/beregn/barnebidrag/service/external/BeregningVedtakConsumer.kt
  bidrag-beregn-barnebidrag/src/main/kotlin/no/nav/bidrag/beregn/barnebidrag/utils/AldersjusteringUtils.kt
  bidrag-beregn-barnebidrag/src/main/kotlin/no/nav/bidrag/beregn/barnebidrag/utils/GrunnlagUtils.kt
  bidrag-vedtak/src/main/kotlin/no/nav/bidrag/beregn/vedtak/Felles.kt
  bidrag-vedtak/src/main/kotlin/no/nav/bidrag/beregn/vedtak/Vedtaksfiltrering.kt
  bidrag-vedtak/src/test/kotlin/no/nav/bidrag/beregn/vedtak/Testdata.kt
  pom.xml
Labels: feature

#537 Rettet feil som gjorde at personobjekter ikke ble referert i responsen
  bidrag-beregn-barnebidrag/src/main/kotlin/no/nav/bidrag/beregn/barnebidrag/service/BeregnAldersjusteringService.kt
  bidrag-beregn-barnebidrag/src/main/kotlin/no/nav/bidrag/beregn/barnebidrag/service/BeregnBarnebidragService.kt
  bidrag-beregn-barnebidrag/src/main/kotlin/no/nav/bidrag/beregn/barnebidrag/service/BeregnBarnetilleggSkattesatsService.kt
  bidrag-beregn-barnebidrag/src/main/kotlin/no/nav/bidrag/beregn/barnebidrag/service/BeregnBidragsevneService.kt
  bidrag-beregn-barnebidrag/src/main/kotlin/no/nav/bidrag/beregn/barnebidrag/service/BeregnBpAndelUnderholdskostnadService.kt
  bidrag-beregn-barnebidrag/src/main/kotlin/no/nav/bidrag/beregn/barnebidrag/service/BeregnEndeligBidragService.kt
  bidrag-beregn-barnebidrag/src/main/kotlin/no/nav/bidrag/beregn/barnebidrag/service/BeregnEndringSjekkGrensePeriodeService.kt
  bidrag-beregn-barnebidrag/src/main/kotlin/no/nav/bidrag/beregn/barnebidrag/service/BeregnEndringSjekkGrenseService.kt
  bidrag-beregn-barnebidrag/src/main/kotlin/no/nav/bidrag/beregn/barnebidrag/service/BeregnIndeksreguleringPrivatAvtaleService.kt
  bidrag-beregn-barnebidrag/src/main/kotlin/no/nav/bidrag/beregn/barnebidrag/service/BeregnNettoBarnetilleggService.kt
  bidrag-beregn-barnebidrag/src/main/kotlin/no/nav/bidrag/beregn/barnebidrag/service/BeregnNettoTilsynsutgiftService.kt
  bidrag-beregn-barnebidrag/src/main/kotlin/no/nav/bidrag/beregn/barnebidrag/service/BeregnSamværsfradragService.kt
  bidrag-beregn-barnebidrag/src/main/kotlin/no/nav/bidrag/beregn/barnebidrag/service/BeregnUnderholdskostnadService.kt
  bidrag-beregn-barnebidrag/src/test/kotlin/no/nav/bidrag/beregn/barnebidrag/api/BeregnAldersjusteringApiTest.kt
  bidrag-beregn-barnebidrag/src/test/kotlin/no/nav/bidrag/beregn/barnebidrag/api/BeregnBarnebidragApiTest.kt
  bidrag-beregn-barnebidrag/src/test/kotlin/no/nav/bidrag/beregn/barnebidrag/api/BeregnEndeligBidragApiTest.kt
  bidrag-beregn-barnebidrag/src/test/kotlin/no/nav/bidrag/beregn/barnebidrag/api/BeregnIndeksregulerPrivatAvtaleApiTest.kt
  bidrag-beregn-barnebidrag/src/test/kotlin/no/nav/bidrag/beregn/barnebidrag/api/FellesApiTest.kt
  bidrag-beregn-barnebidrag/src/test/resources/testfiler/endringsjekkgrenseperiode/endring_sjekk_grense_periode_eksempel1.json
  bidrag-beregn-barnebidrag/src/test/resources/testfiler/endringsjekkgrenseperiode/endring_sjekk_grense_periode_eksempel2.json
  bidrag-beregn-barnebidrag/src/test/resources/testfiler/endringsjekkgrenseperiode/endring_sjekk_grense_periode_eksempel3A.json
  bidrag-beregn-barnebidrag/src/test/resources/testfiler/endringsjekkgrenseperiode/endring_sjekk_grense_periode_eksempel3B.json
  bidrag-beregn-barnebidrag/src/test/resources/testfiler/endringsjekkgrenseperiode/endring_sjekk_grense_periode_eksempel4.json
  bidrag-beregn-barnebidrag/src/test/resources/testfiler/endringsjekkgrenseperiode/endring_sjekk_grense_periode_eksempel5.json
  bidrag-beregn-barnebidrag/src/test/resources/testfiler/endringsjekkgrenseperiode/endring_sjekk_grense_periode_eksempel6A.json
  bidrag-beregn-barnebidrag/src/test/resources/testfiler/endringsjekkgrenseperiode/endring_sjekk_grense_periode_eksempel6B.json
  bidrag-beregn-barnebidrag/src/test/resources/testfiler/endringsjekkgrenseperiode/endring_sjekk_grense_periode_eksempel7A.json
  bidrag-beregn-barnebidrag/src/test/resources/testfiler/endringsjekkgrenseperiode/endring_sjekk_grense_periode_eksempel7B.json
  bidrag-beregn-barnebidrag/src/test/resources/testfiler/endringsjekkgrenseperiode/endring_sjekk_grense_periode_eksempel7C.json
  bidrag-beregn-barnebidrag/src/test/resources/testfiler/endringsjekkgrenseperiode/endring_sjekk_grense_periode_eksempel7D.json
  bidrag-beregn-barnebidrag/src/test/resources/testfiler/endringsjekkgrenseperiode/endring_sjekk_grense_periode_eksempel8.json
  bidrag-beregn-barnebidrag/src/test/resources/testfiler/endringsjekkgrenseperiode/endring_sjekk_grense_periode_eksempel_flere_perioder.json
  bidrag-beregn-barnebidrag/src/test/resources/testfiler/indeksreguleringprivatavtale/privat_avtale_med_indeksregulering.json
  bidrag-beregn-barnebidrag/src/test/resources/testfiler/indeksreguleringprivatavtale/privat_avtale_med_indeksregulering_periode.json
  bidrag-beregn-barnebidrag/src/test/resources/testfiler/indeksreguleringprivatavtale/privat_avtale_med_indeksregulering_siste_periode_med_satt_tildato.json
  bidrag-beregn-barnebidrag/src/test/resources/testfiler/indeksreguleringprivatavtale/privat_avtale_uten_indeksregulering.json
  bidrag-beregn-barnebidrag/src/test/resources/testfiler/nettotilsynsutgift/nettotilsynsutgift_eksempel_flere_perioder.json
  bidrag-beregn-core/src/main/kotlin/no/nav/bidrag/beregn/core/service/BeregnService.kt
Labels: bidrag-beregn-core, bugfix
