Repository navikt/bidrag-beregn-felles, pull requests merged in 2025-02, with the labels that each got.

#463 Fiks for å unngå deling på 0 i beregning av BP's andel
  bidrag-beregn-barnebidrag/src/main/kotlin/no/nav/bidrag/beregn/barnebidrag/beregning/BpAndelUnderholdskostnadBeregning.kt
Labels: bugfix

#464 Rettet feil og utvidet exception ifbm begrenset revurdering
  bidrag-beregn-barnebidrag/src/main/kotlin/no/nav/bidrag/beregn/barnebidrag/BeregnBarnebidragApi.kt
  bidrag-beregn-barnebidrag/src/main/kotlin/no/nav/bidrag/beregn/barnebidrag/bo/EndeligBidragBO.kt
  bidrag-beregn-barnebidrag/src/main/kotlin/no/nav/bidrag/beregn/barnebidrag/service/BeregnBarnebidragService.kt
  bidrag-beregn-barnebidrag/src/main/kotlin/no/nav/bidrag/beregn/barnebidrag/service/BeregnEndeligBidragService.kt
  bidrag-beregn-barnebidrag/src/test/kotlin/no/nav/bidrag/beregn/barnebidrag/api/BeregnBarnebidragApiTest.kt
  bidrag-beregn-barnebidrag/src/test/kotlin/no/nav/bidrag/beregn/barnebidrag/api/BeregnEndeligBidragApiTest.kt
  bidrag-beregn-barnebidrag/src/test/resources/testfiler/barnebidrag/barnebidrag_eksempel3.json
  bidrag-beregn-core/src/main/kotlin/no/nav/bidrag/beregn/core/exception/BegrensetRevurderingLikEllerLavereEnnLøpendeBidragException.kt
  pom.xml
Labels: bidrag-beregn-core, bugfix

#466 Oppdater bidrag-felles.version
  pom.xml
Labels: feature

#465 Feature/juster periodisering
  bidrag-beregn-barnebidrag/src/main/kotlin/no/nav/bidrag/beregn/barnebidrag/beregning/EndeligBidragBeregning.kt
  bidrag-beregn-barnebidrag/src/main/kotlin/no/nav/bidrag/beregn/barnebidrag/beregning/NettoBarnetilleggBeregning.kt
  bidrag-beregn-barnebidrag/src/main/kotlin/no/nav/bidrag/beregn/barnebidrag/mapper/EndeligBidragMapper.kt
  bidrag-beregn-barnebidrag/src/main/kotlin/no/nav/bidrag/beregn/barnebidrag/service/BeregnEndeligBidragService.kt
  bidrag-beregn-barnebidrag/src/test/kotlin/no/nav/bidrag/beregn/barnebidrag/api/BeregnEndeligBidragApiTest.kt
  bidrag-beregn-core/src/main/kotlin/no/nav/bidrag/beregn/core/exception/ExceptionHandlerAdvice.kt
  bidrag-beregn-core/src/main/kotlin/no/nav/bidrag/beregn/core/util/InntektUtil.kt
  bidrag-boforhold/src/main/kotlin/no/nav/bidrag/boforhold/service/BoforholdBarnServiceV3.kt
  bidrag-boforhold/src/test/kotlin/no/nav/bidrag/boforhold/TestUtil.kt
  bidrag-boforhold/src/test/kotlin/no/nav/bidrag/boforhold/service/BoforholdBarnServiceV3Test.kt
Labels: bidrag-beregn-core, feature

#469 Ny delberegning sjekk av grense (totalt, alle perioder)
  bidrag-beregn-barnebidrag/src/main/kotlin/no/nav/bidrag/beregn/barnebidrag/BeregnBarnebidragApi.kt
  bidrag-beregn-barnebidrag/src/main/kotlin/no/nav/bidrag/beregn/barnebidrag/beregning/EndringSjekkGrenseBeregning.kt
  bidrag-beregn-barnebidrag/src/main/kotlin/no/nav/bidrag/beregn/barnebidrag/bo/EndringSjekkGrenseBO.kt
  bidrag-beregn-barnebidrag/src/main/kotlin/no/nav/bidrag/beregn/barnebidrag/mapper/EndringSjekkGrenseMapper.kt
  bidrag-beregn-barnebidrag/src/main/kotlin/no/nav/bidrag/beregn/barnebidrag/service/BeregnBarnebidragService.kt
  bidrag-beregn-barnebidrag/src/main/kotlin/no/nav/bidrag/beregn/barnebidrag/service/BeregnEndringSjekkGrenseService.kt
  bidrag-beregn-barnebidrag/src/test/kotlin/no/nav/bidrag/beregn/barnebidrag/api/BeregnEndringSjekkGrenseApiTest.kt
  bidrag-beregn-barnebidrag/src/test/resources/testfiler/endringsjekkgrense/endring_sjekk_grense_eksempel1.json
  bidrag-beregn-barnebidrag/src/test/resources/testfiler/endringsjekkgrense/endring_sjekk_grense_eksempel2.json
  pom.xml
Labels: feature

#471 Tilpasse beregning for opphørsdato
  bidrag-beregn-barnebidrag/src/main/kotlin/no/nav/bidrag/beregn/barnebidrag/service/BeregnBarnebidragService.kt
  bidrag-beregn-core/src/main/kotlin/no/nav/bidrag/beregn/core/boforhold/BeregnBoforholdService.kt
  bidrag-beregn-core/src/main/kotlin/no/nav/bidrag/beregn/core/inntekt/service/BeregnInntektService.kt
  bidrag-boforhold/src/main/kotlin/no/nav/bidrag/boforhold/BoforholdApi.kt
  bidrag-boforhold/src/main/kotlin/no/nav/bidrag/boforhold/service/BoforholdAndreVoksneService.kt
  bidrag-boforhold/src/main/kotlin/no/nav/bidrag/boforhold/service/BoforholdBarnServiceV3.kt
  pom.xml
Labels: bidrag-beregn-core, feature

#472 Feilfiks opphørsdato periodisering boforhold
  bidrag-beregn-core/src/main/kotlin/no/nav/bidrag/beregn/core/boforhold/BeregnBoforholdService.kt
  bidrag-boforhold/src/main/kotlin/no/nav/bidrag/boforhold/service/BoforholdAndreVoksneService.kt
  bidrag-boforhold/src/main/kotlin/no/nav/bidrag/boforhold/service/BoforholdBarnServiceV3.kt
  bidrag-boforhold/src/main/kotlin/no/nav/bidrag/boforhold/utils/BoforholdPeriodeUtils.kt
Labels: bidrag-beregn-core, feature

#475 Feilfiks opphørsdato periodisering boforhold
  bidrag-beregn-core/src/main/kotlin/no/nav/bidrag/beregn/core/boforhold/BeregnBoforholdService.kt
  bidrag-beregn-core/src/main/kotlin/no/nav/bidrag/beregn/core/inntekt/service/BeregnInntektService.kt
  bidrag-beregn-core/src/main/kotlin/no/nav/bidrag/beregn/core/util/PeriodeUtil.kt
  bidrag-boforhold/src/main/kotlin/no/nav/bidrag/boforhold/utils/BoforholdPeriodeUtils.kt
Labels: bidrag-beregn-core, feature

#476 Feilfiks opphørsdato periodisering
  bidrag-beregn-core/src/main/kotlin/no/nav/bidrag/beregn/core/util/PeriodeUtil.kt
Labels: bidrag-beregn-core, bugfix

#477 Rulle tilbake feilfiks opphørsdato
  bidrag-beregn-core/src/main/kotlin/no/nav/bidrag/beregn/core/util/PeriodeUtil.kt
Labels: bidrag-beregn-core, bugfix

#478 Oppdatert versjon av bidrag-felles og rettet gebyr-test
  bidrag-beregn-barnebidrag/src/test/kotlin/no/nav/bidrag/beregn/barnebidrag/beregning/GebyrBeregningApiTest.kt
  pom.xml
Labels: chore

#479 Periodisering opphørsdato boforhold
  bidrag-beregn-core/src/main/kotlin/no/nav/bidrag/beregn/core/boforhold/BeregnBoforholdService.kt
  bidrag-boforhold/src/main/kotlin/no/nav/bidrag/boforhold/service/BoforholdBarnServiceV3.kt
  bidrag-boforhold/src/main/kotlin/no/nav/bidrag/boforhold/utils/BoforholdPeriodeUtils.kt
Labels: bidrag-beregn-core, feature

#480 Støtte for ny bidrag-felles versjon
  bidrag-beregn-barnebidrag/src/main/kotlin/no/nav/bidrag/beregn/barnebidrag/service/BeregnBarnebidragService.kt
  bidrag-beregn-barnebidrag/src/main/kotlin/no/nav/bidrag/beregn/barnebidrag/service/BeregnEndringSjekkGrensePeriodeService.kt
  bidrag-beregn-barnebidrag/src/test/kotlin/no/nav/bidrag/beregn/barnebidrag/api/BeregnEndringSjekkGrensePeriodeApiTest.kt
  pom.xml
Labels: feature

#482 Kaster exception hvis det er begrenset revurdering og løpende forskud…
  bidrag-beregn-barnebidrag/src/main/kotlin/no/nav/bidrag/beregn/barnebidrag/beregning/EndeligBidragBeregning.kt
  bidrag-beregn-barnebidrag/src/main/kotlin/no/nav/bidrag/beregn/barnebidrag/bo/EndeligBidragBO.kt
  bidrag-beregn-barnebidrag/src/main/kotlin/no/nav/bidrag/beregn/barnebidrag/service/BeregnBarnebidragService.kt
  bidrag-beregn-barnebidrag/src/main/kotlin/no/nav/bidrag/beregn/barnebidrag/service/BeregnEndeligBidragService.kt
  bidrag-beregn-barnebidrag/src/test/kotlin/no/nav/bidrag/beregn/barnebidrag/api/BeregnBarnebidragApiTest.kt
  bidrag-beregn-barnebidrag/src/test/kotlin/no/nav/bidrag/beregn/barnebidrag/api/BeregnEndeligBidragApiTest.kt
  bidrag-beregn-barnebidrag/src/test/resources/testfiler/barnebidrag/barnebidrag_eksempel3A.json
  bidrag-beregn-barnebidrag/src/test/resources/testfiler/barnebidrag/barnebidrag_eksempel3B.json
  bidrag-beregn-barnebidrag/src/test/resources/testfiler/endeligbidrag/endeligbidrag_eksempel10K.json
  bidrag-beregn-barnebidrag/src/test/resources/testfiler/endeligbidrag/endeligbidrag_eksempel10L.json
  bidrag-beregn-core/src/main/kotlin/no/nav/bidrag/beregn/core/exception/BegrensetRevurderingLøpendeForskuddManglerException.kt
  bidrag-beregn-core/src/main/kotlin/no/nav/bidrag/beregn/core/exception/ExceptionHandlerAdvice.kt
Labels: bidrag-beregn-core, feature

#483 Unngå nullpointer i bidragsberegning
  bidrag-beregn-barnebidrag/src/main/kotlin/no/nav/bidrag/beregn/barnebidrag/mapper/EndeligBidragMapper.kt
  bidrag-beregn-barnebidrag/src/main/kotlin/no/nav/bidrag/beregn/barnebidrag/service/BeregnBarnebidragService.kt
  bidrag-beregn-barnebidrag/src/main/kotlin/no/nav/bidrag/beregn/barnebidrag/service/BeregnEndringSjekkGrensePeriodeService.kt
Labels: bugfix

#484 Bostatus bruk gjelderBarnReferanse
  bidrag-beregn-forskudd/src/main/kotlin/no/nav/bidrag/beregn/forskudd/service/ForskuddCoreMapper.kt
  bidrag-beregn-forskudd/src/test/kotlin/no/nav/bidrag/beregn/forskudd/TestUtil.kt
  bidrag-beregn-forskudd/src/test/resources/testfiler/forskudd_eksempel1.json
  bidrag-beregn-forskudd/src/test/resources/testfiler/forskudd_eksempel10.json
  bidrag-beregn-forskudd/src/test/resources/testfiler/forskudd_eksempel11.json
  bidrag-beregn-forskudd/src/test/resources/testfiler/forskudd_eksempel12.json
  bidrag-beregn-forskudd/src/test/resources/testfiler/forskudd_eksempel13.json
  bidrag-beregn-forskudd/src/test/resources/testfiler/forskudd_eksempel14.json
  bidrag-beregn-forskudd/src/test/resources/testfiler/forskudd_eksempel15.json
  bidrag-beregn-forskudd/src/test/resources/testfiler/forskudd_eksempel16.json
  bidrag-beregn-forskudd/src/test/resources/testfiler/forskudd_eksempel17.json
  bidrag-beregn-forskudd/src/test/resources/testfiler/forskudd_eksempel18.json
  bidrag-beregn-forskudd/src/test/resources/testfiler/forskudd_eksempel19.json
  bidrag-beregn-forskudd/src/test/resources/testfiler/forskudd_eksempel2.json
  bidrag-beregn-forskudd/src/test/resources/testfiler/forskudd_eksempel20.json
  bidrag-beregn-forskudd/src/test/resources/testfiler/forskudd_eksempel22.json
  bidrag-beregn-forskudd/src/test/resources/testfiler/forskudd_eksempel23.json
  bidrag-beregn-forskudd/src/test/resources/testfiler/forskudd_eksempel3.json
  bidrag-beregn-forskudd/src/test/resources/testfiler/forskudd_eksempel4.json
  bidrag-beregn-forskudd/src/test/resources/testfiler/forskudd_eksempel5.json
  bidrag-beregn-forskudd/src/test/resources/testfiler/forskudd_eksempel6.json
  bidrag-beregn-forskudd/src/test/resources/testfiler/forskudd_eksempel7.json
  bidrag-beregn-forskudd/src/test/resources/testfiler/forskudd_eksempel8.json
  bidrag-beregn-forskudd/src/test/resources/testfiler/forskudd_eksempel9.json
  bidrag-beregn-forskudd/src/test/resources/testfiler/forskudd_eksempel_flere_perioder.json
  bidrag-beregn-forskudd/src/test/resources/testfiler/forskudd_eksempel_mange_inntektstyper.json
  bidrag-beregn-forskudd/src/test/resources/testfiler/forskudd_test_barnihusstand.json
  bidrag-beregn-forskudd/src/test/resources/testfiler/forskudd_test_inntekt.json
  bidrag-beregn-særbidrag/src/test/resources/testfiler/særbidrag_eksempel1.json
  bidrag-beregn-særbidrag/src/test/resources/testfiler/særbidrag_eksempel2.json
  bidrag-beregn-særbidrag/src/test/resources/testfiler/særbidrag_eksempel3.json
  bidrag-beregn-særbidrag/src/test/resources/testfiler/særbidrag_eksempel4.json
  bidrag-beregn-særbidrag/src/test/resources/testfiler/særbidrag_eksempel5.json
  bidrag-beregn-særbidrag/src/test/resources/testfiler/særbidrag_eksempel6.json
  bidrag-beregn-særbidrag/src/test/resources/testfiler/særbidrag_eksempel7.json
  bidrag-beregn-særbidrag/src/test/resources/testfiler/særbidrag_eksempel8.json
  bidrag-beregn-særbidrag/src/test/resources/testfiler/særbidrag_eksempel_BP_har_betalt_mer_enn_godkjent_beløp.json
  bidrag-beregn-særbidrag/src/test/resources/testfiler/særbidrag_eksempel_BPs_inntekt_mangler.json
  bidrag-beregn-særbidrag/src/test/resources/testfiler/særbidrag_eksempel_barn_regnes_som_voksen.json
  bidrag-beregn-særbidrag/src/test/resources/testfiler/særbidrag_eksempel_barnet_er_selvforsørget.json
  bidrag-beregn-særbidrag/src/test/resources/testfiler/særbidrag_eksempel_beløp_under_forskuddssats.json
  bidrag-beregn-særbidrag/src/test/resources/testfiler/særbidrag_eksempel_deler_av_utgift_betalt_av_BP.json
  bidrag-beregn-særbidrag/src/test/resources/testfiler/særbidrag_eksempel_inntekt_skjønn_mangler_dokumentasjon.json
  bidrag-beregn-særbidrag/src/test/resources/testfiler/særbidrag_eksempel_reduksjon_underholdskostnad_overstyres_til_0.json
  pom.xml
Labels: bidrag-beregn-forskudd, feature

#485 Bugfix/barnebidrag objekthierarki
  bidrag-beregn-barnebidrag/src/main/kotlin/no/nav/bidrag/beregn/barnebidrag/beregning/EndringSjekkGrensePeriodeBeregning.kt
  bidrag-beregn-barnebidrag/src/main/kotlin/no/nav/bidrag/beregn/barnebidrag/service/BeregnBarnebidragService.kt
  bidrag-beregn-barnebidrag/src/test/kotlin/no/nav/bidrag/beregn/barnebidrag/api/BeregnBarnebidragApiTest.kt
Labels: bugfix

#486 Fjernet ingenEndringUnderGrense-indikator fra sluttberegning-objektet
  bidrag-beregn-barnebidrag/src/main/kotlin/no/nav/bidrag/beregn/barnebidrag/bo/EndeligBidragBO.kt
  bidrag-beregn-barnebidrag/src/main/kotlin/no/nav/bidrag/beregn/barnebidrag/service/BeregnEndeligBidragService.kt
  bidrag-beregn-barnebidrag/src/test/kotlin/no/nav/bidrag/beregn/barnebidrag/api/BeregnBarnebidragApiTest.kt
  bidrag-beregn-barnebidrag/src/test/kotlin/no/nav/bidrag/beregn/barnebidrag/api/BeregnEndeligBidragApiTest.kt
  bidrag-beregn-barnebidrag/src/test/kotlin/no/nav/bidrag/beregn/barnebidrag/api/FellesApiTest.kt
  bidrag-beregn-barnebidrag/src/test/resources/testfiler/endringsjekkgrenseperiode/endring_sjekk_grense_periode_eksempel1.json
  bidrag-beregn-barnebidrag/src/test/resources/testfiler/endringsjekkgrenseperiode/endring_sjekk_grense_periode_eksempel2.json
  bidrag-beregn-barnebidrag/src/test/resources/testfiler/endringsjekkgrenseperiode/endring_sjekk_grense_periode_eksempel3A.json
  bidrag-beregn-barnebidrag/src/test/resources/testfiler/endringsjekkgrenseperiode/endring_sjekk_grense_periode_eksempel3B.json
  bidrag-beregn-barnebidrag/src/test/resources/testfiler/endringsjekkgrenseperiode/endring_sjekk_grense_periode_eksempel_flere_perioder.json
  pom.xml
Labels: feature

#488 Lagt inn logikk for å håndtere 18-års-bidrag
  bidrag-beregn-barnebidrag/src/main/kotlin/no/nav/bidrag/beregn/barnebidrag/service/BeregnBarnebidragService.kt
  bidrag-beregn-barnebidrag/src/test/kotlin/no/nav/bidrag/beregn/barnebidrag/api/BeregnBarnebidragApiTest.kt
  bidrag-beregn-barnebidrag/src/test/resources/testfiler/barnebidrag/barnebidrag_eksempel6A.json
  bidrag-beregn-barnebidrag/src/test/resources/testfiler/barnebidrag/barnebidrag_eksempel6B.json
  pom.xml
Labels: feature

#489 Fikset feil i beregning av resultatperioder ifbm beløpshistorikk
  bidrag-beregn-barnebidrag/src/main/kotlin/no/nav/bidrag/beregn/barnebidrag/service/BeregnBarnebidragService.kt
  bidrag-beregn-barnebidrag/src/test/kotlin/no/nav/bidrag/beregn/barnebidrag/api/BeregnBarnebidragApiTest.kt
  bidrag-beregn-barnebidrag/src/test/resources/testfiler/barnebidrag/barnebidrag_eksempel4D.json
Labels: bugfix

#490 Refaktorert kode og fikset en del TODO's i beregning
  bidrag-beregn-barnebidrag/src/main/kotlin/no/nav/bidrag/beregn/barnebidrag/beregning/BarnetilleggSkattesatsBeregning.kt
  bidrag-beregn-barnebidrag/src/main/kotlin/no/nav/bidrag/beregn/barnebidrag/beregning/BidragsevneBeregning.kt
  bidrag-beregn-barnebidrag/src/main/kotlin/no/nav/bidrag/beregn/barnebidrag/beregning/BpAndelUnderholdskostnadBeregning.kt
  bidrag-beregn-barnebidrag/src/main/kotlin/no/nav/bidrag/beregn/barnebidrag/beregning/EndeligBidragBeregning.kt
  bidrag-beregn-barnebidrag/src/main/kotlin/no/nav/bidrag/beregn/barnebidrag/beregning/NettoBarnetilleggBeregning.kt
  bidrag-beregn-barnebidrag/src/main/kotlin/no/nav/bidrag/beregn/barnebidrag/beregning/NettoTilsynsutgiftBeregning.kt
  bidrag-beregn-barnebidrag/src/main/kotlin/no/nav/bidrag/beregn/barnebidrag/beregning/UnderholdskostnadBeregning.kt
  bidrag-beregn-barnebidrag/src/main/kotlin/no/nav/bidrag/beregn/barnebidrag/bo/BarnetilleggSkattesatsBO.kt
  bidrag-beregn-barnebidrag/src/main/kotlin/no/nav/bidrag/beregn/barnebidrag/bo/BidragsevneBO.kt
  bidrag-beregn-barnebidrag/src/main/kotlin/no/nav/bidrag/beregn/barnebidrag/bo/BpAndelUnderholdskostnadBO.kt
  bidrag-beregn-barnebidrag/src/main/kotlin/no/nav/bidrag/beregn/barnebidrag/bo/EndringSjekkGrensePeriodeBO.kt
  bidrag-beregn-barnebidrag/src/main/kotlin/no/nav/bidrag/beregn/barnebidrag/bo/FellesBO.kt
  bidrag-beregn-barnebidrag/src/main/kotlin/no/nav/bidrag/beregn/barnebidrag/bo/IndeksreguleringPrivatAvtaleGrunnlag.kt
  bidrag-beregn-barnebidrag/src/main/kotlin/no/nav/bidrag/beregn/barnebidrag/bo/NettoTilsynsutgiftBO.kt
  bidrag-beregn-barnebidrag/src/main/kotlin/no/nav/bidrag/beregn/barnebidrag/bo/UnderholdskostnadBO.kt
  bidrag-beregn-barnebidrag/src/main/kotlin/no/nav/bidrag/beregn/barnebidrag/mapper/BarnetilleggSkattesatsMapper.kt
  bidrag-beregn-barnebidrag/src/main/kotlin/no/nav/bidrag/beregn/barnebidrag/mapper/BidragsevneMapper.kt
  bidrag-beregn-barnebidrag/src/main/kotlin/no/nav/bidrag/beregn/barnebidrag/mapper/BpAndelUnderholdskostnadMapper.kt
  bidrag-beregn-barnebidrag/src/main/kotlin/no/nav/bidrag/beregn/barnebidrag/mapper/EndeligBidragMapper.kt
  bidrag-beregn-barnebidrag/src/main/kotlin/no/nav/bidrag/beregn/barnebidrag/mapper/EndringSjekkGrensePeriodeMapper.kt
  bidrag-beregn-barnebidrag/src/main/kotlin/no/nav/bidrag/beregn/barnebidrag/mapper/NettoTilsynsutgiftMapper.kt
  bidrag-beregn-barnebidrag/src/main/kotlin/no/nav/bidrag/beregn/barnebidrag/mapper/UnderholdskostnadMapper.kt
  bidrag-beregn-barnebidrag/src/main/kotlin/no/nav/bidrag/beregn/barnebidrag/service/BeregnBarnebidragService.kt
  bidrag-beregn-barnebidrag/src/main/kotlin/no/nav/bidrag/beregn/barnebidrag/service/BeregnBarnetilleggSkattesatsService.kt
  bidrag-beregn-barnebidrag/src/main/kotlin/no/nav/bidrag/beregn/barnebidrag/service/BeregnBidragsevneService.kt
  bidrag-beregn-barnebidrag/src/main/kotlin/no/nav/bidrag/beregn/barnebidrag/service/BeregnBpAndelUnderholdskostnadService.kt
  bidrag-beregn-barnebidrag/src/main/kotlin/no/nav/bidrag/beregn/barnebidrag/service/BeregnEndeligBidragService.kt
  bidrag-beregn-barnebidrag/src/main/kotlin/no/nav/bidrag/beregn/barnebidrag/service/BeregnEndringSjekkGrensePeriodeService.kt
  bidrag-beregn-barnebidrag/src/main/kotlin/no/nav/bidrag/beregn/barnebidrag/service/BeregnEndringSjekkGrenseService.kt
  bidrag-beregn-barnebidrag/src/main/kotlin/no/nav/bidrag/beregn/barnebidrag/service/BeregnIndeksreguleringPrivatAvtaleService.kt
  bidrag-beregn-barnebidrag/src/main/kotlin/no/nav/bidrag/beregn/barnebidrag/service/BeregnNettoBarnetilleggService.kt
  bidrag-beregn-barnebidrag/src/main/kotlin/no/nav/bidrag/beregn/barnebidrag/service/BeregnNettoTilsynsutgiftService.kt
  bidrag-beregn-barnebidrag/src/main/kotlin/no/nav/bidrag/beregn/barnebidrag/service/BeregnSamværsfradragService.kt
  bidrag-beregn-barnebidrag/src/main/kotlin/no/nav/bidrag/beregn/barnebidrag/service/BeregnUnderholdskostnadService.kt
  bidrag-beregn-core/src/main/kotlin/no/nav/bidrag/beregn/core/bo/Sjablon.kt
  bidrag-beregn-core/src/main/kotlin/no/nav/bidrag/beregn/core/service/BeregnService.kt
  bidrag-beregn-core/src/main/kotlin/no/nav/bidrag/beregn/core/service/mapper/CoreMapper.kt
  bidrag-beregn-forskudd/src/main/kotlin/no/nav/bidrag/beregn/forskudd/service/BeregnForskuddService.kt
  bidrag-beregn-forskudd/src/main/kotlin/no/nav/bidrag/beregn/forskudd/service/ForskuddCoreMapper.kt
  bidrag-beregn-særbidrag/src/main/kotlin/no/nav/bidrag/beregn/særbidrag/service/BeregnSærbidragService.kt
  bidrag-beregn-særbidrag/src/main/kotlin/no/nav/bidrag/beregn/særbidrag/service/mapper/BPAndelSærbidragCoreMapper.kt
  bidrag-beregn-særbidrag/src/main/kotlin/no/nav/bidrag/beregn/særbidrag/service/mapper/BidragsevneCoreMapper.kt
Labels: bidrag-beregn-forskudd, bidrag-beregn-core, feature

#495 Skal bruke BELØPSHISTORIKK_BIDRAG_18_ÅR for å sjekke 12%-regel for 18…
  bidrag-beregn-barnebidrag/src/main/kotlin/no/nav/bidrag/beregn/barnebidrag/mapper/EndringSjekkGrensePeriodeMapper.kt
  bidrag-beregn-barnebidrag/src/main/kotlin/no/nav/bidrag/beregn/barnebidrag/service/BeregnBarnebidragService.kt
  bidrag-beregn-barnebidrag/src/main/kotlin/no/nav/bidrag/beregn/barnebidrag/service/BeregnEndringSjekkGrensePeriodeService.kt
  bidrag-beregn-barnebidrag/src/test/kotlin/no/nav/bidrag/beregn/barnebidrag/api/BeregnBarnebidragApiTest.kt
  bidrag-beregn-barnebidrag/src/test/kotlin/no/nav/bidrag/beregn/barnebidrag/api/BeregnEndringSjekkGrensePeriodeApiTest.kt
  bidrag-beregn-barnebidrag/src/test/resources/testfiler/barnebidrag/barnebidrag_eksempel7A.json
  bidrag-beregn-barnebidrag/src/test/resources/testfiler/barnebidrag/barnebidrag_eksempel7B.json
  bidrag-beregn-barnebidrag/src/test/resources/testfiler/endringsjekkgrenseperiode/endring_sjekk_grense_periode_eksempel4.json
  bidrag-beregn-barnebidrag/src/test/resources/testfiler/endringsjekkgrenseperiode/endring_sjekk_grense_periode_eksempel5.json
  bidrag-beregn-barnebidrag/src/test/resources/testfiler/endringsjekkgrenseperiode/endring_sjekk_grense_periode_eksempel6A.json
  bidrag-beregn-barnebidrag/src/test/resources/testfiler/endringsjekkgrenseperiode/endring_sjekk_grense_periode_eksempel6B.json
Labels: feature

#497 Justert litt på test i sluttberegning som treffer hvis inntekt er 0
  bidrag-beregn-barnebidrag/src/main/kotlin/no/nav/bidrag/beregn/barnebidrag/beregning/EndeligBidragBeregning.kt
Labels: bugfix

#505 Quickfix boforhold nullpointer
  bidrag-boforhold/src/main/kotlin/no/nav/bidrag/boforhold/service/BoforholdBarnServiceV3.kt
Labels: bugfix

#507 Ny logikk for boforhold for søknadsbarn i 18-årssaker
  bidrag-boforhold/src/main/kotlin/no/nav/bidrag/boforhold/dto/Boforhold.kt
  bidrag-boforhold/src/main/kotlin/no/nav/bidrag/boforhold/service/BoforholdBarnServiceV3.kt
  bidrag-boforhold/src/test/kotlin/no/nav/bidrag/boforhold/TestUtil.kt
  bidrag-boforhold/src/test/kotlin/no/nav/bidrag/boforhold/service/BoforholdBarnServiceV3Test.kt
  pom.xml
Labels: feature
