Repository navikt/bidrag-beregn-felles, pull requests merged in 2025-06, with the labels that each got.

#606 Endret level på noe av loggingen fra debug til info
  bidrag-beregn-barnebidrag/src/main/kotlin/no/nav/bidrag/beregn/barnebidrag/service/BeregnAldersjusteringService.kt
  bidrag-beregn-barnebidrag/src/main/kotlin/no/nav/bidrag/beregn/barnebidrag/service/BeregnBarnebidragService.kt
  bidrag-beregn-forskudd/src/main/kotlin/no/nav/bidrag/beregn/forskudd/service/BeregnForskuddService.kt
  bidrag-beregn-særbidrag/src/main/kotlin/no/nav/bidrag/beregn/særbidrag/service/BeregnSærbidragService.kt
  bidrag-boforhold/src/test/kotlin/no/nav/bidrag/boforhold/service/BoforholdBarnServiceV3Test.kt
  pom.xml
Labels: bidrag-beregn-forskudd, feature

#614 Finn siste manuelle vedtak hvis resultat er VO i aldersjustering
  bidrag-beregn-barnebidrag/src/main/kotlin/no/nav/bidrag/beregn/barnebidrag/service/AldersjusteringOrchestrator.kt
  bidrag-beregn-barnebidrag/src/main/kotlin/no/nav/bidrag/beregn/barnebidrag/service/VedtakService.kt
Labels: feature

#615 Ignorer reskode MANGL_DOK_AV_INNT_BM ved evnesjekk
  bidrag-beregn-barnebidrag/src/main/kotlin/no/nav/bidrag/beregn/barnebidrag/service/AldersjusteringOrchestrator.kt
Labels: feature

#617 Feature/forskudd sluttdato 18år
  bidrag-beregn-core/src/main/kotlin/no/nav/bidrag/beregn/core/service/mapper/CoreMapper.kt
  bidrag-beregn-forskudd/src/main/kotlin/no/nav/bidrag/beregn/forskudd/core/ForskuddCore.kt
  bidrag-beregn-forskudd/src/main/kotlin/no/nav/bidrag/beregn/forskudd/core/bo/CoreBO.kt
  bidrag-beregn-forskudd/src/main/kotlin/no/nav/bidrag/beregn/forskudd/core/dto/CoreDTO.kt
  bidrag-beregn-forskudd/src/main/kotlin/no/nav/bidrag/beregn/forskudd/core/periode/ForskuddPeriode.kt
  bidrag-beregn-forskudd/src/main/kotlin/no/nav/bidrag/beregn/forskudd/service/BeregnForskuddService.kt
  bidrag-beregn-forskudd/src/main/kotlin/no/nav/bidrag/beregn/forskudd/service/ForskuddCoreMapper.kt
  bidrag-beregn-forskudd/src/test/kotlin/no/nav/bidrag/beregn/forskudd/api/BeregnForskuddApiTest.kt
  bidrag-beregn-forskudd/src/test/kotlin/no/nav/bidrag/beregn/forskudd/service/ForskuddCoreMapperTest.kt
  bidrag-beregn-forskudd/src/test/resources/testfiler/forskudd_eksempel1A.json
  pom.xml
Labels: bidrag-beregn-forskudd, bidrag-beregn-core, feature

#621 Fikse aldersjustering beregning
  bidrag-beregn-barnebidrag/src/main/kotlin/no/nav/bidrag/beregn/barnebidrag/service/AldersjusteringOrchestrator.kt
  bidrag-beregn-barnebidrag/src/main/kotlin/no/nav/bidrag/beregn/barnebidrag/service/VedtakService.kt
Labels: feature

#623 Fikse aldersjustering beregning hent beløp siste periode
  bidrag-beregn-barnebidrag/src/main/kotlin/no/nav/bidrag/beregn/barnebidrag/service/AldersjusteringOrchestrator.kt
Labels: feature

#630 Aldersjustering sjekk for nyeste ident ved filtrering av stønadsendring i vedtak
  bidrag-beregn-barnebidrag/src/main/kotlin/no/nav/bidrag/beregn/barnebidrag/service/AldersjusteringOrchestrator.kt
  bidrag-beregn-barnebidrag/src/test/kotlin/no/nav/bidrag/beregn/barnebidrag/service/AldersjusteringOrchestratorTest.kt
Labels: feature

#632 Refaktorering og tilpasse for manuell aldersjustering
  bidrag-beregn-barnebidrag/src/main/kotlin/no/nav/bidrag/beregn/barnebidrag/service/AldersjusteringOrchestrator.kt
  bidrag-beregn-barnebidrag/src/main/kotlin/no/nav/bidrag/beregn/barnebidrag/service/VedtakService.kt
  bidrag-beregn-barnebidrag/src/main/kotlin/no/nav/bidrag/beregn/barnebidrag/service/external/BeregningStønadConsumer.kt
  bidrag-beregn-barnebidrag/src/main/kotlin/no/nav/bidrag/beregn/barnebidrag/utils/GrunnlagUtils.kt
  bidrag-beregn-barnebidrag/src/test/kotlin/no/nav/bidrag/beregn/barnebidrag/testdata/Testdata.kt
Labels: feature
