Repository navikt/bidrag-beregn-felles, pull requests merged in 2025-05, with the labels that each got.

#567 Feilfiks og endringer aldersjustering
  bidrag-beregn-barnebidrag/src/main/kotlin/no/nav/bidrag/beregn/barnebidrag/service/AldersjusteringOrchestrator.kt
  bidrag-beregn-barnebidrag/src/test/kotlin/no/nav/bidrag/beregn/barnebidrag/service/AldersjusteringOrchestratorTest.kt
  bidrag-boforhold/src/test/kotlin/no/nav/bidrag/boforhold/service/BoforholdBarnServiceV3Test.kt
Labels: feature

#570 Feilfiks og endringer aldersjustering
  bidrag-beregn-barnebidrag/src/main/kotlin/no/nav/bidrag/beregn/barnebidrag/service/AldersjusteringOrchestrator.kt
  bidrag-beregn-barnebidrag/src/main/kotlin/no/nav/bidrag/beregn/barnebidrag/service/VedtakService.kt
Labels: feature

#571 Feilfiks og endringer aldersjustering
  bidrag-beregn-barnebidrag/src/main/kotlin/no/nav/bidrag/beregn/barnebidrag/service/AldersjusteringOrchestrator.kt
Labels: feature

#572 Feilfiks og endringer aldersjustering
  bidrag-beregn-barnebidrag/src/main/kotlin/no/nav/bidrag/beregn/barnebidrag/service/AldersjusteringOrchestrator.kt
  bidrag-vedtak/src/main/kotlin/no/nav/bidrag/beregn/vedtak/Utvidelser.kt
Labels: bugfix

#573 Oppgrader felles
  pom.xml
Labels: feature

#574 Oppgrader felles
  pom.xml
Labels: feature

#576 Feilfiks aldersjustering
  bidrag-beregn-barnebidrag/src/main/kotlin/no/nav/bidrag/beregn/barnebidrag/service/AldersjusteringOrchestrator.kt
Labels: feature

#577 Feilfiks aldersjustering
  bidrag-vedtak/src/main/kotlin/no/nav/bidrag/beregn/vedtak/Vedtaksfiltrering.kt
Labels: bugfix

#575 Oppgrader felles
  pom.xml
Labels: feature

#578 Feilfiks aldersjustering
  bidrag-beregn-barnebidrag/src/main/kotlin/no/nav/bidrag/beregn/barnebidrag/service/AldersjusteringOrchestrator.kt
  bidrag-beregn-barnebidrag/src/test/kotlin/no/nav/bidrag/beregn/barnebidrag/service/AldersjusteringOrchestratorTest.kt
Labels: bugfix

#579 Feilfiks aldersjustering
  bidrag-beregn-barnebidrag/src/main/kotlin/no/nav/bidrag/beregn/barnebidrag/service/AldersjusteringOrchestrator.kt
Labels: feature

#581 Feilfiks aldersjustering
  bidrag-beregn-barnebidrag/src/main/kotlin/no/nav/bidrag/beregn/barnebidrag/service/AldersjusteringOrchestrator.kt
Labels: feature

#582 Feilfiks aldersjustering
  bidrag-beregn-barnebidrag/src/main/kotlin/no/nav/bidrag/beregn/barnebidrag/service/AldersjusteringOrchestrator.kt
  bidrag-beregn-barnebidrag/src/test/kotlin/no/nav/bidrag/beregn/barnebidrag/service/AldersjusteringOrchestratorTest.kt
Labels: feature

#583 Feilfiks aldersjustering
  bidrag-beregn-barnebidrag/src/main/kotlin/no/nav/bidrag/beregn/barnebidrag/service/AldersjusteringOrchestrator.kt
Labels: feature

#588 Rename DELT_BOSTED_BELØP_0 begrunnelse
  bidrag-beregn-barnebidrag/src/main/kotlin/no/nav/bidrag/beregn/barnebidrag/service/AldersjusteringOrchestrator.kt
Labels: feature

#589 Privat avtale ikke manuell oppgave
  bidrag-beregn-barnebidrag/src/main/kotlin/no/nav/bidrag/beregn/barnebidrag/service/AldersjusteringOrchestrator.kt
  pom.xml
Labels: feature

#590 Opphørsdato aldersjustering
  bidrag-beregn-barnebidrag/src/main/kotlin/no/nav/bidrag/beregn/barnebidrag/service/AldersjusteringOrchestrator.kt
Labels: feature

#591 Aldersjustering sjekk for nyeste ident for kravhaver
  bidrag-beregn-barnebidrag/src/main/kotlin/no/nav/bidrag/beregn/barnebidrag/service/AldersjusteringOrchestrator.kt
  bidrag-beregn-barnebidrag/src/test/kotlin/no/nav/bidrag/beregn/barnebidrag/service/AldersjusteringOrchestratorTest.kt
  pom.xml
Labels: feature

#593 Aldersjustering endringer navn på begrunnelser
  bidrag-beregn-barnebidrag/src/main/kotlin/no/nav/bidrag/beregn/barnebidrag/service/AldersjusteringOrchestrator.kt
  bidrag-beregn-barnebidrag/src/test/kotlin/no/nav/bidrag/beregn/barnebidrag/service/AldersjusteringOrchestratorTest.kt
Labels: feature

#594 Aldersjustering: Barnetilsyn med stønad hentes fra forrige vedtak og …
  bidrag-beregn-barnebidrag/src/main/kotlin/no/nav/bidrag/beregn/barnebidrag/beregning/UnderholdskostnadBeregning.kt
  bidrag-beregn-barnebidrag/src/main/kotlin/no/nav/bidrag/beregn/barnebidrag/bo/AldersjusteringBeregningGrunnlag.kt
  bidrag-beregn-barnebidrag/src/main/kotlin/no/nav/bidrag/beregn/barnebidrag/bo/UnderholdskostnadBO.kt
  bidrag-beregn-barnebidrag/src/main/kotlin/no/nav/bidrag/beregn/barnebidrag/mapper/AldersjusteringMapper.kt
  bidrag-beregn-barnebidrag/src/main/kotlin/no/nav/bidrag/beregn/barnebidrag/service/BeregnAldersjusteringService.kt
  bidrag-beregn-barnebidrag/src/main/kotlin/no/nav/bidrag/beregn/barnebidrag/service/BeregnBpAndelUnderholdskostnadService.kt
  bidrag-beregn-barnebidrag/src/main/kotlin/no/nav/bidrag/beregn/barnebidrag/service/BeregnEndeligBidragService.kt
  bidrag-beregn-barnebidrag/src/main/kotlin/no/nav/bidrag/beregn/barnebidrag/service/BeregnNettoBarnetilleggService.kt
  bidrag-beregn-barnebidrag/src/test/kotlin/no/nav/bidrag/beregn/barnebidrag/api/BeregnAldersjusteringApiTest.kt
  bidrag-beregn-barnebidrag/src/test/kotlin/no/nav/bidrag/beregn/barnebidrag/service/AldersjusteringOrchestratorTest.kt
  bidrag-beregn-barnebidrag/src/test/resources/testfiler/aldersjustering/aldersjustering_eksempel1.json
  bidrag-beregn-core/src/main/kotlin/no/nav/bidrag/beregn/core/service/BeregnService.kt
  pom.xml
Labels: bidrag-beregn-core, feature

#595 Aldersjustering endringer navn på begrunnelser
  bidrag-beregn-barnebidrag/src/main/kotlin/no/nav/bidrag/beregn/barnebidrag/service/VedtakService.kt
Labels: feature

#596 Feilfiks aldersjustering justering BP evne
  bidrag-beregn-barnebidrag/src/main/kotlin/no/nav/bidrag/beregn/barnebidrag/service/AldersjusteringOrchestrator.kt
Labels: bugfix

#600 Rulle tilbake endring aldersjustering
  bidrag-beregn-barnebidrag/src/main/kotlin/no/nav/bidrag/beregn/barnebidrag/service/AldersjusteringOrchestrator.kt
Labels: feature
