Repository navikt/bidrag-beregn-felles, pull requests merged in 2025-04, with the labels that each got.

#538 Legg til tester aldersjustering
  bidrag-beregn-barnebidrag/src/main/kotlin/no/nav/bidrag/beregn/barnebidrag/service/AldersjusteringOrchestrator.kt
  bidrag-beregn-barnebidrag/src/test/kotlin/no/nav/bidrag/beregn/barnebidrag/service/AldersjusteringOrchestratorTest.kt
  bidrag-beregn-barnebidrag/src/test/kotlin/no/nav/bidrag/beregn/barnebidrag/testdata/Testdata.kt
  bidrag-beregn-barnebidrag/src/test/kotlin/no/nav/bidrag/beregn/barnebidrag/testdata/TestdataGrunnlag.kt
  bidrag-beregn-barnebidrag/src/test/resources/testfiler/aldersjustering_orkestrator/vedtak_aldersjustering_1.json
Labels: feature

#539 Oppdatert kaps- og ligs-mapping med kodeendringer
  bidrag-inntekt/src/main/resources/files/mapping_kaps.yaml
  bidrag-inntekt/src/main/resources/files/mapping_ligs.yaml
Labels: bidrag-inntekt, feature

#540 Rettet feil i aldersjustering-beregning hvis det ligger inne stønadse…
  bidrag-beregn-barnebidrag/src/main/kotlin/no/nav/bidrag/beregn/barnebidrag/mapper/AldersjusteringMapper.kt
  bidrag-beregn-barnebidrag/src/test/kotlin/no/nav/bidrag/beregn/barnebidrag/api/BeregnAldersjusteringApiTest.kt
  bidrag-beregn-barnebidrag/src/test/resources/testfiler/aldersjustering/aldersjustering_eksempel10.json
  bidrag-beregn-barnebidrag/src/test/resources/testfiler/aldersjustering/aldersjustering_eksempel11.json
  bidrag-beregn-barnebidrag/src/test/resources/testfiler/aldersjustering/aldersjustering_eksempel12.json
  bidrag-beregn-barnebidrag/src/test/resources/testfiler/aldersjustering/aldersjustering_eksempel13.json
  bidrag-beregn-barnebidrag/src/test/resources/testfiler/aldersjustering/aldersjustering_eksempel14.json
  bidrag-beregn-barnebidrag/src/test/resources/testfiler/aldersjustering/aldersjustering_eksempel7.json
  bidrag-beregn-barnebidrag/src/test/resources/testfiler/aldersjustering/aldersjustering_eksempel8.json
  bidrag-beregn-barnebidrag/src/test/resources/testfiler/aldersjustering/aldersjustering_eksempel9.json
Labels: bugfix

#541 Refaktorering privat avtale delberegning
  bidrag-beregn-barnebidrag/src/main/kotlin/no/nav/bidrag/beregn/barnebidrag/mapper/EndringSjekkGrensePeriodeMapper.kt
  bidrag-beregn-barnebidrag/src/main/kotlin/no/nav/bidrag/beregn/barnebidrag/service/BeregnBarnebidragService.kt
  bidrag-beregn-barnebidrag/src/main/kotlin/no/nav/bidrag/beregn/barnebidrag/service/BeregnIndeksreguleringPrivatAvtaleService.kt
  bidrag-beregn-barnebidrag/src/main/kotlin/no/nav/bidrag/beregn/barnebidrag/service/VedtakService.kt
  bidrag-beregn-barnebidrag/src/test/kotlin/no/nav/bidrag/beregn/barnebidrag/api/BeregnBarnebidragApiTest.kt
  bidrag-beregn-barnebidrag/src/test/kotlin/no/nav/bidrag/beregn/barnebidrag/api/BeregnIndeksregulerPrivatAvtaleApiTest.kt
  bidrag-beregn-barnebidrag/src/test/kotlin/no/nav/bidrag/beregn/barnebidrag/testdata/Testdata.kt
  bidrag-beregn-barnebidrag/src/test/resources/testfiler/endringsjekkgrenseperiode/endring_sjekk_grense_periode_eksempel8.json
  bidrag-indeksregulering/src/main/kotlin/no/nav/bidrag/indeksregulering/service/IndeksreguleringService.kt
  pom.xml
Labels: feature

#542 Sett riktig indeksår hvis privat avtale ikke indeksreguleres
  bidrag-beregn-barnebidrag/src/main/kotlin/no/nav/bidrag/beregn/barnebidrag/service/BeregnIndeksreguleringPrivatAvtaleService.kt
Labels: feature

#543 Beregning endring-sjekk-grense-periode refererer til enten beløpshist…
  bidrag-beregn-barnebidrag/src/main/kotlin/no/nav/bidrag/beregn/barnebidrag/beregning/EndringSjekkGrensePeriodeBeregning.kt
  bidrag-beregn-barnebidrag/src/test/kotlin/no/nav/bidrag/beregn/barnebidrag/api/BeregnEndringSjekkGrensePeriodeApiTest.kt
  bidrag-beregn-barnebidrag/src/test/resources/testfiler/endringsjekkgrenseperiode/endring_sjekk_grense_periode_eksempel8A.json
  bidrag-beregn-barnebidrag/src/test/resources/testfiler/endringsjekkgrenseperiode/endring_sjekk_grense_periode_eksempel8B.json
  bidrag-beregn-barnebidrag/src/test/resources/testfiler/endringsjekkgrenseperiode/endring_sjekk_grense_periode_eksempel8C.json
Labels: feature

#546 Boforhold søknadsbarn over 18 i bidrag
  bidrag-boforhold/src/main/kotlin/no/nav/bidrag/boforhold/service/BoforholdBarnServiceV3.kt
  bidrag-boforhold/src/test/kotlin/no/nav/bidrag/boforhold/service/BoforholdBarnServiceV3Test.kt
Labels: feature

#548 Skal feile hvis nytt aldersjustert beløp er lavere enn eller lik løpe…
  bidrag-beregn-barnebidrag/src/main/kotlin/no/nav/bidrag/beregn/barnebidrag/service/BeregnAldersjusteringService.kt
  bidrag-beregn-barnebidrag/src/test/kotlin/no/nav/bidrag/beregn/barnebidrag/api/BeregnAldersjusteringApiTest.kt
  bidrag-beregn-core/src/main/kotlin/no/nav/bidrag/beregn/core/exception/AldersjusteringLavereEnnEllerLikLøpendeBidragException.kt
Labels: bidrag-beregn-core, bugfix

#547 Feilhåndtering aldersjustering
  bidrag-beregn-barnebidrag/src/main/kotlin/no/nav/bidrag/beregn/barnebidrag/service/AldersjusteringOrchestrator.kt
  bidrag-beregn-barnebidrag/src/main/kotlin/no/nav/bidrag/beregn/barnebidrag/service/VedtakService.kt
  bidrag-beregn-barnebidrag/src/test/kotlin/no/nav/bidrag/beregn/barnebidrag/service/AldersjusteringOrchestratorTest.kt
  bidrag-vedtak/src/main/kotlin/no/nav/bidrag/beregn/vedtak/Utvidelser.kt
Labels: feature

#557 Feilfiks og endringer aldersjustering
  bidrag-beregn-barnebidrag/src/main/kotlin/no/nav/bidrag/beregn/barnebidrag/service/AldersjusteringOrchestrator.kt
  bidrag-beregn-barnebidrag/src/test/kotlin/no/nav/bidrag/beregn/barnebidrag/service/AldersjusteringOrchestratorTest.kt
Labels: feature

#562 Feilfiks og endringer aldersjustering
  bidrag-beregn-barnebidrag/src/main/kotlin/no/nav/bidrag/beregn/barnebidrag/service/AldersjusteringOrchestrator.kt
Labels: bugfix

#563 Rettet feil for å forhindre at negativt beløp returneres ved aldersju…
  bidrag-beregn-barnebidrag/src/main/kotlin/no/nav/bidrag/beregn/barnebidrag/beregning/EndeligBidragBeregning.kt
Labels: bugfix

#564 Fikset beregning ved delt bosted for aldersjustering
  bidrag-beregn-barnebidrag/src/main/kotlin/no/nav/bidrag/beregn/barnebidrag/beregning/EndeligBidragBeregning.kt
  bidrag-beregn-barnebidrag/src/main/kotlin/no/nav/bidrag/beregn/barnebidrag/bo/AldersjusteringBeregningGrunnlag.kt
  bidrag-beregn-barnebidrag/src/main/kotlin/no/nav/bidrag/beregn/barnebidrag/bo/EndeligBidragBO.kt
  bidrag-beregn-barnebidrag/src/main/kotlin/no/nav/bidrag/beregn/barnebidrag/mapper/AldersjusteringMapper.kt
  bidrag-beregn-barnebidrag/src/main/kotlin/no/nav/bidrag/beregn/barnebidrag/service/BeregnAldersjusteringService.kt
  bidrag-beregn-barnebidrag/src/main/kotlin/no/nav/bidrag/beregn/barnebidrag/service/BeregnEndeligBidragService.kt
  bidrag-beregn-barnebidrag/src/test/kotlin/no/nav/bidrag/beregn/barnebidrag/api/BeregnAldersjusteringApiTest.kt
  bidrag-beregn-barnebidrag/src/test/resources/testfiler/aldersjustering/aldersjustering_eksempel3A.json
  bidrag-beregn-barnebidrag/src/test/resources/testfiler/aldersjustering/aldersjustering_eksempel3B.json
  pom.xml
Labels: feature

#565 Feilfiks og endringer aldersjustering
  bidrag-beregn-barnebidrag/src/main/kotlin/no/nav/bidrag/beregn/barnebidrag/service/AldersjusteringOrchestrator.kt
  bidrag-beregn-barnebidrag/src/main/kotlin/no/nav/bidrag/beregn/barnebidrag/service/external/BeregningPersonConsumer.kt
Labels: feature

#566 Aldersjustering: Til-periode på kopi-objekter settes til null
  bidrag-beregn-barnebidrag/src/main/kotlin/no/nav/bidrag/beregn/barnebidrag/service/BeregnAldersjusteringService.kt
  bidrag-beregn-barnebidrag/src/test/kotlin/no/nav/bidrag/beregn/barnebidrag/api/BeregnAldersjusteringApiTest.kt
Labels: bugfix
